import { type Kanji } from "../syllabary-kanji";

export const KotobeLevelTheme = [
    { level: 1, theme: "School & Time" },
    { level: 2, theme: "Basic Daily Actions" },
    { level: 3, theme: "Food & Eating" },
    { level: 4, theme: "Home & Rooms" },
    { level: 5, theme: "Transportation" },
    { level: 6, theme: "Weather & Nature" },
    { level: 7, theme: "Family & Body" },
    { level: 8, theme: "Movement & Physical Actions" },
    { level: 9, theme: "Places Around Town" },
    { level: 10, theme: "Shopping & Stores" },
    { level: 11, theme: "Learning & Studying" },
    { level: 12, theme: "Objects & Media" },
    { level: 13, theme: "Weeks, Months & Frequency" },
    { level: 14, theme: "Personal Information & Time" },
    { level: 15, theme: "Basic Descriptions" },
    { level: 16, theme: "Conditions & Descriptions" },
    { level: 17, theme: "Everyday States & Expressions" },
    { level: 18, theme: "Useful Everyday Vocabulary" },
    { level: 19, theme: "Everyday Routine" },
    { level: 20, theme: "Food & Restaurants" },
    { level: 21, theme: "Getting Around Town" },
    { level: 22, theme: "Work & Communication" },
    { level: 23, theme: "People, Feelings & Conversation" },
    { level: 24, theme: "Household & Personal Items" },
    { level: 25, theme: "Descriptions & Quantities" },
    { level: 26, theme: "Speech & Language Family" },
    { level: 27, theme: "Hand & Action Family" },
    { level: 28, theme: "Mind & Emotion Family" },
    { level: 29, theme: "Day & Time Family" },
    { level: 30, theme: "Water & Liquid Family" },
];

export const n5Kotoba_lv1: Kanji[] = [
    // Round 1 — 20 related vocabulary items
    { kanji: "時間", kana: "じかん", romaji: "jikan", meaning: "time", indonesian: "waktu", level: "N5", round: 1 },
    { kanji: "時計", kana: "とけい", romaji: "tokei", meaning: "clock; watch", indonesian: "clock; watch", level: "N5", round: 1 },
    { kanji: "今日", kana: "きょう", romaji: "kyou", meaning: "today", indonesian: "hari ini", level: "N5", round: 1 },
    { kanji: "昨日", kana: "きのう", romaji: "kinou", meaning: "yesterday", indonesian: "kemarin", level: "N5", round: 1 },
    { kanji: "明日", kana: "あした", romaji: "ashita", meaning: "tomorrow", indonesian: "besok", level: "N5", round: 1 },
    { kanji: "学校", kana: "がっこう", romaji: "gakkou", meaning: "school", indonesian: "sekolah", level: "N5", round: 1 },
    { kanji: "学生", kana: "がくせい", romaji: "gakusei", meaning: "student", indonesian: "pelajar", level: "N5", round: 1 },
    { kanji: "先生", kana: "せんせい", romaji: "sensei", meaning: "teacher", indonesian: "guru", level: "N5", round: 1 },
    { kanji: "教室", kana: "きょうしつ", romaji: "kyoushitsu", meaning: "classroom", indonesian: "classroom", level: "N5", round: 1 },
    { kanji: "大学", kana: "だいがく", romaji: "daigaku", meaning: "university", indonesian: "universitas", level: "N5", round: 1 },
    { kanji: "午前", kana: "ごぜん", romaji: "gozen", meaning: "a.m.; morning", indonesian: "pagi; sebelum tengah hari", level: "N5", round: 1 },
    { kanji: "午後", kana: "ごご", romaji: "gogo", meaning: "p.m.; afternoon", indonesian: "siang; setelah tengah hari", level: "N5", round: 1 },
    { kanji: "半分", kana: "はんぶん", romaji: "hanbun", meaning: "half", indonesian: "setengah", level: "N5", round: 1 },
    { kanji: "授業", kana: "じゅぎょう", romaji: "jugyou", meaning: "class; lesson", indonesian: "pelajaran; kelas", level: "N4", round: 1 },
    { kanji: "勉強", kana: "べんきょう", romaji: "benkyou", meaning: "study", indonesian: "belajar", level: "N5", round: 1 },
    { kanji: "教科書", kana: "きょうかしょ", romaji: "kyoukasho", meaning: "textbook", indonesian: "buku pelajaran", level: "N4", round: 1 },
    { kanji: "宿題", kana: "しゅくだい", romaji: "shukudai", meaning: "homework", indonesian: "pekerjaan rumah", level: "N5", round: 1 },
    { kanji: "試験", kana: "しけん", romaji: "shiken", meaning: "exam", indonesian: "ujian", level: "N4", round: 1 },
    { kanji: "休み時間", kana: "やすみじかん", romaji: "yasumijikan", meaning: "break time", indonesian: "waktu istirahat", level: "N4", round: 1 },
    { kanji: "校長", kana: "こうちょう", romaji: "kouchou", meaning: "school principal", indonesian: "kepala sekolah", level: "N4", round: 1 },

    // Round 2 — 20 related vocabulary items
    { kanji: "食べる", kana: "たべる", romaji: "taberu", meaning: "to eat", indonesian: "makan", level: "N5", round: 2 },
    { kanji: "飲む", kana: "のむ", romaji: "nomu", meaning: "to drink", indonesian: "minum", level: "N5", round: 2 },
    { kanji: "行く", kana: "いく", romaji: "iku", meaning: "to go", indonesian: "pergi", level: "N5", round: 2 },
    { kanji: "来る", kana: "くる", romaji: "kuru", meaning: "to come", indonesian: "datang", level: "N5", round: 2 },
    { kanji: "帰る", kana: "かえる", romaji: "kaeru", meaning: "to return", indonesian: "pulang; kembali", level: "N5", round: 2 },
    { kanji: "見る", kana: "みる", romaji: "miru", meaning: "to see", indonesian: "melihat", level: "N5", round: 2 },
    { kanji: "聞く", kana: "きく", romaji: "kiku", meaning: "to listen; ask", indonesian: "mendengar; bertanya", level: "N5", round: 2 },
    { kanji: "話す", kana: "はなす", romaji: "hanasu", meaning: "to speak", indonesian: "berbicara", level: "N5", round: 2 },
    { kanji: "読む", kana: "よむ", romaji: "yomu", meaning: "to read", indonesian: "membaca", level: "N5", round: 2 },
    { kanji: "書く", kana: "かく", romaji: "kaku", meaning: "to write", indonesian: "menulis", level: "N5", round: 2 },
    { kanji: "起こす", kana: "おこす", romaji: "okosu", meaning: "to wake someone up", indonesian: "membangunkan", level: "N4", round: 2 },
    { kanji: "戻る", kana: "もどる", romaji: "modoru", meaning: "to return; go back", indonesian: "kembali", level: "N4", round: 2 },
    { kanji: "見せる", kana: "みせる", romaji: "miseru", meaning: "to show", indonesian: "menunjukkan", level: "N5", round: 2 },
    { kanji: "聞こえる", kana: "きこえる", romaji: "kikoeru", meaning: "to be audible", indonesian: "terdengar", level: "N4", round: 2 },
    { kanji: "話し合う", kana: "はなしあう", romaji: "hanashiau", meaning: "to discuss", indonesian: "berdiskusi", level: "N3", round: 2 },
    { kanji: "読み方", kana: "よみかた", romaji: "yomikata", meaning: "way of reading", indonesian: "cara membaca", level: "N4", round: 2 },
    { kanji: "書き方", kana: "かきかた", romaji: "kakikata", meaning: "way of writing", indonesian: "cara menulis", level: "N4", round: 2 },
    { kanji: "歩き回る", kana: "あるきまわる", romaji: "arukimawaru", meaning: "to walk around", indonesian: "berjalan berkeliling", level: "N3", round: 2 },
    { kanji: "出発する", kana: "しゅっぱつする", romaji: "shuppatsu suru", meaning: "to depart", indonesian: "berangkat", level: "N4", round: 2 },
    { kanji: "到着する", kana: "とうちゃくする", romaji: "touchaku suru", meaning: "to arrive", indonesian: "tiba", level: "N4", round: 2 },

    // Round 3 — 20 related vocabulary items
    { kanji: "食べ物", kana: "たべもの", romaji: "tabemono", meaning: "food", indonesian: "makanan", level: "N5", round: 3 },
    { kanji: "飲み物", kana: "のみもの", romaji: "nomimono", meaning: "drink (beverage)", indonesian: "drink (beverage)", level: "N5", round: 3 },
    { kanji: "朝ご飯", kana: "あさごはん", romaji: "asagohan", meaning: "breakfast", indonesian: "sarapan", level: "N5", round: 3 },
    { kanji: "買う", kana: "かう", romaji: "kau", meaning: "to buy", indonesian: "membeli", level: "N5", round: 3 },
    { kanji: "野菜", kana: "やさい", romaji: "yasai", meaning: "vegetables", indonesian: "sayuran", level: "N5", round: 3 },
    { kanji: "果物", kana: "くだもの", romaji: "kudamono", meaning: "fruit", indonesian: "buah", level: "N5", round: 3 },
    { kanji: "牛肉", kana: "ぎゅうにく", romaji: "gyuuniku", meaning: "beef", indonesian: "daging sapi", level: "N5", round: 3 },
    { kanji: "鳥肉", kana: "とりにく", romaji: "toriniku", meaning: "chicken meat", indonesian: "daging ayam", level: "N5", round: 3 },
    { kanji: "魚料理", kana: "さかなりょうり", romaji: "sakana ryouri", meaning: "fish dish", indonesian: "fish dish", level: "N4", round: 3 },
    { kanji: "飲み水", kana: "のみみず", romaji: "nomimizu", meaning: "drinking water", indonesian: "drinking water", level: "N4", round: 3 },
    { kanji: "夕飯", kana: "ゆうはん", romaji: "yuuhan", meaning: "evening meal; dinner", indonesian: "makan malam", level: "N4", round: 3 },
    { kanji: "食事", kana: "しょくじ", romaji: "shokuji", meaning: "meal", indonesian: "makanan; waktu makan", level: "N4", round: 3 },
    { kanji: "料理", kana: "りょうり", romaji: "ryouri", meaning: "cooking; cuisine", indonesian: "masakan", level: "N4", round: 3 },
    { kanji: "野菜料理", kana: "やさいりょうり", romaji: "yasai ryouri", meaning: "vegetable dish", indonesian: "masakan sayur", level: "N4", round: 3 },
    { kanji: "果汁", kana: "かじゅう", romaji: "kajuu", meaning: "fruit juice", indonesian: "jus buah", level: "N3", round: 3 },
    { kanji: "牛肉料理", kana: "ぎゅうにくりょうり", romaji: "gyuuniku ryouri", meaning: "beef dish", indonesian: "masakan daging sapi", level: "N4", round: 3 },
    { kanji: "鶏肉", kana: "とりにく", romaji: "toriniku", meaning: "chicken meat", indonesian: "daging ayam", level: "N4", round: 3 },
    { kanji: "魚介類", kana: "ぎょかいるい", romaji: "gyokairui", meaning: "seafood", indonesian: "makanan laut", level: "N3", round: 3 },
    { kanji: "食堂", kana: "しょくどう", romaji: "shokudou", meaning: "cafeteria; dining hall", indonesian: "kantin; ruang makan", level: "N4", round: 3 },
    { kanji: "飲食店", kana: "いんしょくてん", romaji: "inshokuten", meaning: "restaurant; eatery", indonesian: "rumah makan", level: "N3", round: 3 },

    // Round 4 — 20 related vocabulary items
    { kanji: "家", kana: "いえ", romaji: "ie", meaning: "house; home", indonesian: "rumah", level: "N5", round: 4 },
    { kanji: "部屋", kana: "へや", romaji: "heya", meaning: "room", indonesian: "kamar", level: "N5", round: 4 },
    { kanji: "玄関", kana: "げんかん", romaji: "genkan", meaning: "entrance", indonesian: "pintu masuk", level: "N5", round: 4 },
    { kanji: "台所", kana: "だいどころ", romaji: "daidokoro", meaning: "kitchen", indonesian: "dapur", level: "N5", round: 4 },
    { kanji: "開ける", kana: "あける", romaji: "akeru", meaning: "to open", indonesian: "membuka", level: "N5", round: 4 },
    { kanji: "閉める", kana: "しめる", romaji: "shimeru", meaning: "to close", indonesian: "menutup", level: "N5", round: 4 },
    { kanji: "窓", kana: "まど", romaji: "mado", meaning: "window", indonesian: "window", level: "N5", round: 4 },
    { kanji: "戸", kana: "と", romaji: "to", meaning: "door", indonesian: "door", level: "N5", round: 4 },
    { kanji: "机", kana: "つくえ", romaji: "tsukue", meaning: "desk", indonesian: "desk", level: "N5", round: 4 },
    { kanji: "椅子", kana: "いす", romaji: "isu", meaning: "chair", indonesian: "chair", level: "N5", round: 4 },
    { kanji: "寝室", kana: "しんしつ", romaji: "shinshitsu", meaning: "bedroom", indonesian: "kamar tidur", level: "N4", round: 4 },
    { kanji: "居間", kana: "いま", romaji: "ima", meaning: "living room", indonesian: "ruang keluarga", level: "N4", round: 4 },
    { kanji: "浴室", kana: "よくしつ", romaji: "yokushitsu", meaning: "bathroom", indonesian: "kamar mandi", level: "N3", round: 4 },
    { kanji: "屋根", kana: "やね", romaji: "yane", meaning: "roof", indonesian: "atap", level: "N4", round: 4 },
    { kanji: "階段", kana: "かいだん", romaji: "kaidan", meaning: "stairs", indonesian: "tangga", level: "N4", round: 4 },
    { kanji: "庭", kana: "にわ", romaji: "niwa", meaning: "garden; yard", indonesian: "halaman; kebun", level: "N5", round: 4 },
    { kanji: "床", kana: "ゆか", romaji: "yuka", meaning: "floor", indonesian: "lantai", level: "N4", round: 4 },
    { kanji: "壁", kana: "かべ", romaji: "kabe", meaning: "wall", indonesian: "dinding", level: "N4", round: 4 },
    { kanji: "天井", kana: "てんじょう", romaji: "tenjou", meaning: "ceiling", indonesian: "langit-langit", level: "N3", round: 4 },
    { kanji: "家具", kana: "かぐ", romaji: "kagu", meaning: "furniture", indonesian: "perabot", level: "N4", round: 4 },

    // Round 5 — 20 related vocabulary items
    { kanji: "電車", kana: "でんしゃ", romaji: "densha", meaning: "train", indonesian: "kereta", level: "N5", round: 5 },
    { kanji: "駅前", kana: "えきまえ", romaji: "ekimae", meaning: "in front of the station", indonesian: "in front of the station", level: "N5", round: 5 },
    { kanji: "自転車", kana: "じてんしゃ", romaji: "jitensha", meaning: "bicycle", indonesian: "sepeda", level: "N5", round: 5 },
    { kanji: "車", kana: "くるま", romaji: "kuruma", meaning: "car", indonesian: "mobil", level: "N5", round: 5 },
    { kanji: "乗る", kana: "のる", romaji: "noru", meaning: "to ride", indonesian: "naik; mengendarai", level: "N5", round: 5 },
    { kanji: "降りる", kana: "おりる", romaji: "oriru", meaning: "to get off", indonesian: "turun", level: "N5", round: 5 },
    { kanji: "地下鉄", kana: "ちかてつ", romaji: "chikatetsu", meaning: "subway", indonesian: "subway", level: "N5", round: 5 },
    { kanji: "新幹線", kana: "しんかんせん", romaji: "shinkansen", meaning: "bullet train", indonesian: "bullet train", level: "N4", round: 5 },
    { kanji: "飛行機", kana: "ひこうき", romaji: "hikouki", meaning: "airplane", indonesian: "pesawat", level: "N5", round: 5 },
    { kanji: "自動車", kana: "じどうしゃ", romaji: "jidousha", meaning: "automobile", indonesian: "automobile", level: "N4", round: 5 },
    { kanji: "バス停", kana: "バスてい", romaji: "basutei", meaning: "bus stop", indonesian: "halte bus", level: "N5", round: 5 },
    { kanji: "道路", kana: "どうろ", romaji: "douro", meaning: "road", indonesian: "jalan raya", level: "N4", round: 5 },
    { kanji: "線路", kana: "せんろ", romaji: "senro", meaning: "railway track", indonesian: "rel kereta", level: "N3", round: 5 },
    { kanji: "乗車", kana: "じょうしゃ", romaji: "jousha", meaning: "boarding a vehicle", indonesian: "naik kendaraan", level: "N3", round: 5 },
    { kanji: "下車", kana: "げしゃ", romaji: "gesha", meaning: "getting off a vehicle", indonesian: "turun dari kendaraan", level: "N3", round: 5 },
    { kanji: "発車", kana: "はっしゃ", romaji: "hassha", meaning: "departure of a vehicle", indonesian: "keberangkatan kendaraan", level: "N3", round: 5 },
    { kanji: "停車", kana: "ていしゃ", romaji: "teisha", meaning: "stopping a vehicle", indonesian: "kendaraan berhenti", level: "N3", round: 5 },
    { kanji: "終点", kana: "しゅうてん", romaji: "shuuten", meaning: "last stop; terminal", indonesian: "pemberhentian terakhir", level: "N3", round: 5 },
    { kanji: "快速", kana: "かいそく", romaji: "kaisoku", meaning: "rapid train", indonesian: "kereta cepat", level: "N3", round: 5 },
    { kanji: "普通列車", kana: "ふつうれっしゃ", romaji: "futsuu ressha", meaning: "local train", indonesian: "kereta lokal", level: "N3", round: 5 },

    // Round 6 — 20 related vocabulary items
    { kanji: "天気", kana: "てんき", romaji: "tenki", meaning: "weather", indonesian: "cuaca", level: "N5", round: 6 },
    { kanji: "雨", kana: "あめ", romaji: "ame", meaning: "rain", indonesian: "hujan", level: "N5", round: 6 },
    { kanji: "雪", kana: "ゆき", romaji: "yuki", meaning: "snow", indonesian: "salju", level: "N5", round: 6 },
    { kanji: "風", kana: "かぜ", romaji: "kaze", meaning: "wind", indonesian: "angin", level: "N5", round: 6 },
    { kanji: "青空", kana: "あおぞら", romaji: "aozora", meaning: "blue sky", indonesian: "blue sky", level: "N4", round: 6 },
    { kanji: "夕方", kana: "ゆうがた", romaji: "yuugata", meaning: "evening", indonesian: "sore", level: "N5", round: 6 },
    { kanji: "朝", kana: "あさ", romaji: "asa", meaning: "morning", indonesian: "pagi", level: "N5", round: 6 },
    { kanji: "夜", kana: "よる", romaji: "yoru", meaning: "night", indonesian: "malam", level: "N5", round: 6 },
    { kanji: "昼", kana: "ひる", romaji: "hiru", meaning: "daytime; noon", indonesian: "siang", level: "N5", round: 6 },
    { kanji: "暑い", kana: "あつい", romaji: "atsui", meaning: "hot (weather)", indonesian: "hot (weather)", level: "N5", round: 6 },
    { kanji: "晴れ", kana: "はれ", romaji: "hare", meaning: "clear weather", indonesian: "cuaca cerah", level: "N5", round: 6 },
    { kanji: "曇り", kana: "くもり", romaji: "kumori", meaning: "cloudy weather", indonesian: "cuaca berawan", level: "N5", round: 6 },
    { kanji: "台風", kana: "たいふう", romaji: "taifuu", meaning: "typhoon", indonesian: "topan", level: "N4", round: 6 },
    { kanji: "気温", kana: "きおん", romaji: "kion", meaning: "air temperature", indonesian: "suhu udara", level: "N3", round: 6 },
    { kanji: "春", kana: "はる", romaji: "haru", meaning: "spring", indonesian: "musim semi", level: "N5", round: 6 },
    { kanji: "夏", kana: "なつ", romaji: "natsu", meaning: "summer", indonesian: "musim panas", level: "N5", round: 6 },
    { kanji: "秋", kana: "あき", romaji: "aki", meaning: "autumn", indonesian: "musim gugur", level: "N5", round: 6 },
    { kanji: "冬", kana: "ふゆ", romaji: "fuyu", meaning: "winter", indonesian: "musim dingin", level: "N5", round: 6 },
    { kanji: "夕日", kana: "ゆうひ", romaji: "yuuhi", meaning: "setting sun", indonesian: "matahari terbenam", level: "N4", round: 6 },
    { kanji: "朝日", kana: "あさひ", romaji: "asahi", meaning: "morning sun", indonesian: "matahari pagi", level: "N4", round: 6 },

    // Round 7 — 20 related vocabulary items
    { kanji: "家族", kana: "かぞく", romaji: "kazoku", meaning: "family", indonesian: "keluarga", level: "N5", round: 7 },
    { kanji: "両親", kana: "りょうしん", romaji: "ryoushin", meaning: "parents", indonesian: "orang tua", level: "N4", round: 7 },
    { kanji: "主人", kana: "しゅじん", romaji: "shujin", meaning: "husband (humble)", indonesian: "suami", level: "N4", round: 7 },
    { kanji: "奥さん", kana: "おくさん", romaji: "okusan", meaning: "wife", indonesian: "istri", level: "N5", round: 7 },
    { kanji: "子ども", kana: "こども", romaji: "kodomo", meaning: "child", indonesian: "anak", level: "N5", round: 7 },
    { kanji: "目", kana: "め", romaji: "me", meaning: "eye", indonesian: "mata", level: "N5", round: 7 },
    { kanji: "耳", kana: "みみ", romaji: "mimi", meaning: "ear", indonesian: "telinga", level: "N5", round: 7 },
    { kanji: "鼻", kana: "はな", romaji: "hana", meaning: "nose", indonesian: "hidung", level: "N5", round: 7 },
    { kanji: "口", kana: "くち", romaji: "kuchi", meaning: "mouth", indonesian: "mulut", level: "N5", round: 7 },
    { kanji: "手", kana: "て", romaji: "te", meaning: "hand", indonesian: "tangan", level: "N5", round: 7 },
    { kanji: "父", kana: "ちち", romaji: "chichi", meaning: "father", indonesian: "ayah", level: "N5", round: 7 },
    { kanji: "母", kana: "はは", romaji: "haha", meaning: "mother", indonesian: "ibu", level: "N5", round: 7 },
    { kanji: "兄", kana: "あに", romaji: "ani", meaning: "older brother", indonesian: "kakak laki-laki", level: "N5", round: 7 },
    { kanji: "姉", kana: "あね", romaji: "ane", meaning: "older sister", indonesian: "kakak perempuan", level: "N5", round: 7 },
    { kanji: "弟", kana: "おとうと", romaji: "otouto", meaning: "younger brother", indonesian: "adik laki-laki", level: "N5", round: 7 },
    { kanji: "妹", kana: "いもうと", romaji: "imouto", meaning: "younger sister", indonesian: "adik perempuan", level: "N5", round: 7 },
    { kanji: "頭", kana: "あたま", romaji: "atama", meaning: "head", indonesian: "kepala", level: "N5", round: 7 },
    { kanji: "顔", kana: "かお", romaji: "kao", meaning: "face", indonesian: "wajah", level: "N5", round: 7 },
    { kanji: "指", kana: "ゆび", romaji: "yubi", meaning: "finger", indonesian: "jari", level: "N4", round: 7 },
    { kanji: "体", kana: "からだ", romaji: "karada", meaning: "body", indonesian: "tubuh", level: "N5", round: 7 },

    // Round 8 — 20 related vocabulary items
    { kanji: "足", kana: "あし", romaji: "ashi", meaning: "foot; leg", indonesian: "kaki", level: "N5", round: 8 },
    { kanji: "立つ", kana: "たつ", romaji: "tatsu", meaning: "to stand", indonesian: "berdiri", level: "N5", round: 8 },
    { kanji: "座る", kana: "すわる", romaji: "suwaru", meaning: "to sit", indonesian: "duduk", level: "N5", round: 8 },
    { kanji: "歩く", kana: "あるく", romaji: "aruku", meaning: "to walk", indonesian: "berjalan", level: "N5", round: 8 },
    { kanji: "走る", kana: "はしる", romaji: "hashiru", meaning: "to run", indonesian: "berlari", level: "N5", round: 8 },
    { kanji: "止まる", kana: "とまる", romaji: "tomaru", meaning: "to stop", indonesian: "berhenti", level: "N5", round: 8 },
    { kanji: "入る", kana: "はいる", romaji: "hairu", meaning: "to enter", indonesian: "masuk", level: "N5", round: 8 },
    { kanji: "出る", kana: "でる", romaji: "deru", meaning: "to leave", indonesian: "keluar; meninggalkan", level: "N5", round: 8 },
    { kanji: "遊ぶ", kana: "あそぶ", romaji: "asobu", meaning: "to play", indonesian: "bermain", level: "N5", round: 8 },
    { kanji: "泳ぐ", kana: "およぐ", romaji: "oyogu", meaning: "to swim", indonesian: "berenang", level: "N5", round: 8 },
    { kanji: "上がる", kana: "あがる", romaji: "agaru", meaning: "to go up", indonesian: "naik", level: "N5", round: 8 },
    { kanji: "下がる", kana: "さがる", romaji: "sagaru", meaning: "to go down", indonesian: "turun", level: "N4", round: 8 },
    { kanji: "上る", kana: "のぼる", romaji: "noboru", meaning: "to climb; go up", indonesian: "mendaki; naik", level: "N5", round: 8 },
    { kanji: "下りる", kana: "おりる", romaji: "oriru", meaning: "to go down", indonesian: "turun", level: "N5", round: 8 },
    { kanji: "動く", kana: "うごく", romaji: "ugoku", meaning: "to move", indonesian: "bergerak", level: "N4", round: 8 },
    { kanji: "動かす", kana: "うごかす", romaji: "ugokasu", meaning: "to move something", indonesian: "menggerakkan", level: "N4", round: 8 },
    { kanji: "飛ぶ", kana: "とぶ", romaji: "tobu", meaning: "to fly; jump", indonesian: "terbang; melompat", level: "N4", round: 8 },
    { kanji: "跳ぶ", kana: "とぶ", romaji: "tobu", meaning: "to jump", indonesian: "melompat", level: "N3", round: 8 },
    { kanji: "曲げる", kana: "まげる", romaji: "mageru", meaning: "to bend", indonesian: "membengkokkan", level: "N4", round: 8 },
    { kanji: "伸びる", kana: "のびる", romaji: "nobiru", meaning: "to stretch; extend", indonesian: "memanjang; meregang", level: "N4", round: 8 },

    // Round 9 — 20 related vocabulary items
    { kanji: "会社", kana: "かいしゃ", romaji: "kaisha", meaning: "company", indonesian: "perusahaan", level: "N5", round: 9 },
    { kanji: "会社員", kana: "かいしゃいん", romaji: "kaishain", meaning: "office worker", indonesian: "karyawan kantor", level: "N5", round: 9 },
    { kanji: "銀行", kana: "ぎんこう", romaji: "ginkou", meaning: "bank", indonesian: "bank", level: "N5", round: 9 },
    { kanji: "病院", kana: "びょういん", romaji: "byouin", meaning: "hospital", indonesian: "rumah sakit", level: "N5", round: 9 },
    { kanji: "図書館", kana: "としょかん", romaji: "toshokan", meaning: "library", indonesian: "perpustakaan", level: "N5", round: 9 },
    { kanji: "郵便局", kana: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "post office", indonesian: "post office", level: "N5", round: 9 },
    { kanji: "公園", kana: "こうえん", romaji: "kouen", meaning: "park", indonesian: "taman", level: "N5", round: 9 },
    { kanji: "空港", kana: "くうこう", romaji: "kuukou", meaning: "airport", indonesian: "bandara", level: "N5", round: 9 },
    { kanji: "教会", kana: "きょうかい", romaji: "kyoukai", meaning: "church", indonesian: "church", level: "N4", round: 9 },
    { kanji: "交番", kana: "こうばん", romaji: "kouban", meaning: "police box", indonesian: "police box", level: "N5", round: 9 },
    { kanji: "市役所", kana: "しやくしょ", romaji: "shiyakusho", meaning: "city hall", indonesian: "balai kota", level: "N4", round: 9 },
    { kanji: "役所", kana: "やくしょ", romaji: "yakusho", meaning: "government office", indonesian: "kantor pemerintahan", level: "N4", round: 9 },
    { kanji: "警察署", kana: "けいさつしょ", romaji: "keisatsusho", meaning: "police station", indonesian: "kantor polisi", level: "N4", round: 9 },
    { kanji: "消防署", kana: "しょうぼうしょ", romaji: "shoubousho", meaning: "fire station", indonesian: "kantor pemadam kebakaran", level: "N3", round: 9 },
    { kanji: "駅", kana: "えき", romaji: "eki", meaning: "station", indonesian: "stasiun", level: "N5", round: 9 },
    { kanji: "工場", kana: "こうじょう", romaji: "koujou", meaning: "factory", indonesian: "pabrik", level: "N4", round: 9 },
    { kanji: "市場", kana: "いちば", romaji: "ichiba", meaning: "market", indonesian: "pasar", level: "N3", round: 9 },
    { kanji: "寺", kana: "てら", romaji: "tera", meaning: "Buddhist temple", indonesian: "kuil Buddha", level: "N4", round: 9 },
    { kanji: "神社", kana: "じんじゃ", romaji: "jinja", meaning: "Shinto shrine", indonesian: "kuil Shinto", level: "N4", round: 9 },
    { kanji: "美術館", kana: "びじゅつかん", romaji: "bijutsukan", meaning: "art museum", indonesian: "museum seni", level: "N4", round: 9 },

    // Round 10 — 20 related vocabulary items
    { kanji: "売る", kana: "うる", romaji: "uru", meaning: "to sell", indonesian: "menjual", level: "N5", round: 10 },
    { kanji: "店員", kana: "てんいん", romaji: "tenin", meaning: "shop clerk", indonesian: "shop clerk", level: "N5", round: 10 },
    { kanji: "財布", kana: "さいふ", romaji: "saifu", meaning: "wallet", indonesian: "dompet", level: "N5", round: 10 },
    { kanji: "切手", kana: "きって", romaji: "kitte", meaning: "postage stamp", indonesian: "postage stamp", level: "N5", round: 10 },
    { kanji: "荷物", kana: "にもつ", romaji: "nimotsu", meaning: "baggage", indonesian: "barang bawaan", level: "N5", round: 10 },
    { kanji: "品物", kana: "しなもの", romaji: "shinamono", meaning: "goods", indonesian: "barang", level: "N4", round: 10 },
    { kanji: "値段", kana: "ねだん", romaji: "nedan", meaning: "price", indonesian: "harga", level: "N5", round: 10 },
    { kanji: "喫茶店", kana: "きっさてん", romaji: "kissaten", meaning: "coffee shop", indonesian: "coffee shop", level: "N4", round: 10 },
    { kanji: "本屋", kana: "ほんや", romaji: "honya", meaning: "bookstore", indonesian: "bookstore", level: "N5", round: 10 },
    { kanji: "花屋", kana: "はなや", romaji: "hanaya", meaning: "florist", indonesian: "florist", level: "N5", round: 10 },
    { kanji: "商品", kana: "しょうひん", romaji: "shouhin", meaning: "product; merchandise", indonesian: "produk; barang dagangan", level: "N3", round: 10 },
    { kanji: "買い手", kana: "かいて", romaji: "kaite", meaning: "buyer", indonesian: "pembeli", level: "N3", round: 10 },
    { kanji: "売り手", kana: "うりて", romaji: "urite", meaning: "seller", indonesian: "penjual", level: "N3", round: 10 },
    { kanji: "売店", kana: "ばいてん", romaji: "baiten", meaning: "shop; kiosk", indonesian: "kios; toko", level: "N3", round: 10 },
    { kanji: "値札", kana: "ねふだ", romaji: "nefuda", meaning: "price tag", indonesian: "label harga", level: "N3", round: 10 },
    { kanji: "現金", kana: "げんきん", romaji: "genkin", meaning: "cash", indonesian: "uang tunai", level: "N4", round: 10 },
    { kanji: "お金", kana: "おかね", romaji: "okane", meaning: "money", indonesian: "uang", level: "N5", round: 10 },
    { kanji: "百貨店", kana: "ひゃっかてん", romaji: "hyakkaten", meaning: "department store", indonesian: "toserba", level: "N4", round: 10 },
    { kanji: "商店", kana: "しょうてん", romaji: "shouten", meaning: "shop; store", indonesian: "toko", level: "N4", round: 10 },
    { kanji: "店長", kana: "てんちょう", romaji: "tenchou", meaning: "store manager", indonesian: "kepala toko", level: "N3", round: 10 },

    // Round 11 — 20 related vocabulary items
    { kanji: "教える", kana: "おしえる", romaji: "oshieru", meaning: "to teach", indonesian: "mengajar", level: "N5", round: 11 },
    { kanji: "習う", kana: "ならう", romaji: "narau", meaning: "to learn", indonesian: "belajar", level: "N5", round: 11 },
    { kanji: "覚える", kana: "おぼえる", romaji: "oboeru", meaning: "to memorize", indonesian: "menghafal", level: "N5", round: 11 },
    { kanji: "忘れる", kana: "わすれる", romaji: "wasureru", meaning: "to forget", indonesian: "lupa", level: "N5", round: 11 },
    { kanji: "考える", kana: "かんがえる", romaji: "kangaeru", meaning: "to think", indonesian: "berpikir", level: "N5", round: 11 },
    { kanji: "答える", kana: "こたえる", romaji: "kotaeru", meaning: "to answer", indonesian: "menjawab", level: "N5", round: 11 },
    { kanji: "質問する", kana: "しつもんする", romaji: "shitsumon suru", meaning: "to ask a question", indonesian: "bertanya", level: "N5", round: 11 },
    { kanji: "手伝う", kana: "てつだう", romaji: "tetsudau", meaning: "to help", indonesian: "membantu", level: "N5", round: 11 },
    { kanji: "始まる", kana: "はじまる", romaji: "hajimaru", meaning: "to begin (intransitive)", indonesian: "mulai", level: "N5", round: 11 },
    { kanji: "始める", kana: "はじめる", romaji: "hajimeru", meaning: "to begin (transitive)", indonesian: "memulai", level: "N5", round: 11 },
    { kanji: "学ぶ", kana: "まなぶ", romaji: "manabu", meaning: "to learn; study", indonesian: "belajar", level: "N3", round: 11 },
    { kanji: "練習する", kana: "れんしゅうする", romaji: "renshuu suru", meaning: "to practice", indonesian: "berlatih", level: "N4", round: 11 },
    { kanji: "復習する", kana: "ふくしゅうする", romaji: "fukushuu suru", meaning: "to review", indonesian: "mengulang pelajaran", level: "N4", round: 11 },
    { kanji: "予習する", kana: "よしゅうする", romaji: "yoshuu suru", meaning: "to prepare a lesson", indonesian: "mempelajari terlebih dahulu", level: "N3", round: 11 },
    { kanji: "理解する", kana: "りかいする", romaji: "rikai suru", meaning: "to understand", indonesian: "memahami", level: "N3", round: 11 },
    { kanji: "調べる", kana: "しらべる", romaji: "shiraberu", meaning: "to investigate; look up", indonesian: "mencari tahu; memeriksa", level: "N4", round: 11 },
    { kanji: "直す", kana: "なおす", romaji: "naosu", meaning: "to fix; correct", indonesian: "memperbaiki", level: "N4", round: 11 },
    { kanji: "間違える", kana: "まちがえる", romaji: "machigaeru", meaning: "to make a mistake", indonesian: "melakukan kesalahan", level: "N4", round: 11 },
    { kanji: "続ける", kana: "つづける", romaji: "tsuzukeru", meaning: "to continue", indonesian: "melanjutkan", level: "N4", round: 11 },
    { kanji: "止める", kana: "やめる", romaji: "yameru", meaning: "to stop; quit", indonesian: "berhenti", level: "N4", round: 11 },

    // Round 12 — 20 related vocabulary items
    { kanji: "電話", kana: "でんわ", romaji: "denwa", meaning: "telephone", indonesian: "telepon", level: "N5", round: 12 },
    { kanji: "新聞", kana: "しんぶん", romaji: "shinbun", meaning: "newspaper", indonesian: "newspaper", level: "N5", round: 12 },
    { kanji: "映画", kana: "えいが", romaji: "eiga", meaning: "movie", indonesian: "movie", level: "N5", round: 12 },
    { kanji: "音楽", kana: "おんがく", romaji: "ongaku", meaning: "music", indonesian: "music", level: "N5", round: 12 },
    { kanji: "鉛筆", kana: "えんぴつ", romaji: "enpitsu", meaning: "pencil", indonesian: "pencil", level: "N5", round: 12 },
    { kanji: "消しゴム", kana: "けしゴム", romaji: "keshigomu", meaning: "eraser", indonesian: "eraser", level: "N5", round: 12 },
    { kanji: "辞書", kana: "じしょ", romaji: "jisho", meaning: "dictionary", indonesian: "dictionary", level: "N5", round: 12 },
    { kanji: "眼鏡", kana: "めがね", romaji: "megane", meaning: "glasses", indonesian: "glasses", level: "N5", round: 12 },
    { kanji: "写真", kana: "しゃしん", romaji: "shashin", meaning: "photograph", indonesian: "photograph", level: "N5", round: 12 },
    { kanji: "意味", kana: "いみ", romaji: "imi", meaning: "meaning", indonesian: "arti", level: "N5", round: 12 },
    { kanji: "本", kana: "ほん", romaji: "hon", meaning: "book", indonesian: "buku", level: "N5", round: 12 },
    { kanji: "ノート", kana: "ノート", romaji: "nooto", meaning: "notebook", indonesian: "buku catatan", level: "N5", round: 12 },
    { kanji: "手帳", kana: "てちょう", romaji: "techou", meaning: "pocket notebook; planner", indonesian: "buku agenda", level: "N4", round: 12 },
    { kanji: "文房具", kana: "ぶんぼうぐ", romaji: "bunbougu", meaning: "stationery", indonesian: "alat tulis", level: "N3", round: 12 },
    { kanji: "封筒", kana: "ふうとう", romaji: "fuutou", meaning: "envelope", indonesian: "amplop", level: "N4", round: 12 },
    { kanji: "葉書", kana: "はがき", romaji: "hagaki", meaning: "postcard", indonesian: "kartu pos", level: "N4", round: 12 },
    { kanji: "雑誌", kana: "ざっし", romaji: "zasshi", meaning: "magazine", indonesian: "majalah", level: "N4", round: 12 },
    { kanji: "漫画", kana: "まんが", romaji: "manga", meaning: "manga; comic", indonesian: "komik; manga", level: "N4", round: 12 },
    { kanji: "画面", kana: "がめん", romaji: "gamen", meaning: "screen", indonesian: "layar", level: "N3", round: 12 },
    { kanji: "映像", kana: "えいぞう", romaji: "eizou", meaning: "video image; footage", indonesian: "gambar video; rekaman", level: "N3", round: 12 },

    // Round 13 — 20 related vocabulary items
    { kanji: "毎日", kana: "まいにち", romaji: "mainichi", meaning: "every day", indonesian: "every day", level: "N5", round: 13 },
    { kanji: "毎週", kana: "まいしゅう", romaji: "maishuu", meaning: "every week", indonesian: "every week", level: "N5", round: 13 },
    { kanji: "毎年", kana: "まいとし", romaji: "maitoshi", meaning: "every year", indonesian: "every year", level: "N5", round: 13 },
    { kanji: "先週", kana: "せんしゅう", romaji: "senshuu", meaning: "last week", indonesian: "last week", level: "N5", round: 13 },
    { kanji: "今週", kana: "こんしゅう", romaji: "konshuu", meaning: "this week", indonesian: "this week", level: "N5", round: 13 },
    { kanji: "来週", kana: "らいしゅう", romaji: "raishuu", meaning: "next week", indonesian: "next week", level: "N5", round: 13 },
    { kanji: "先月", kana: "せんげつ", romaji: "sengetsu", meaning: "last month", indonesian: "last month", level: "N5", round: 13 },
    { kanji: "今月", kana: "こんげつ", romaji: "kongetsu", meaning: "this month", indonesian: "this month", level: "N5", round: 13 },
    { kanji: "来月", kana: "らいげつ", romaji: "raigetsu", meaning: "next month", indonesian: "next month", level: "N5", round: 13 },
    { kanji: "去年", kana: "きょねん", romaji: "kyonen", meaning: "last year", indonesian: "last year", level: "N5", round: 13 },
    { kanji: "月曜日", kana: "げつようび", romaji: "getsuyoubi", meaning: "Monday", indonesian: "Senin", level: "N5", round: 13 },
    { kanji: "火曜日", kana: "かようび", romaji: "kayoubi", meaning: "Tuesday", indonesian: "Selasa", level: "N5", round: 13 },
    { kanji: "水曜日", kana: "すいようび", romaji: "suiyoubi", meaning: "Wednesday", indonesian: "Rabu", level: "N5", round: 13 },
    { kanji: "木曜日", kana: "もくようび", romaji: "mokuyoubi", meaning: "Thursday", indonesian: "Kamis", level: "N5", round: 13 },
    { kanji: "金曜日", kana: "きんようび", romaji: "kinyoubi", meaning: "Friday", indonesian: "Jumat", level: "N5", round: 13 },
    { kanji: "土曜日", kana: "どようび", romaji: "doyoubi", meaning: "Saturday", indonesian: "Sabtu", level: "N5", round: 13 },
    { kanji: "日曜日", kana: "にちようび", romaji: "nichiyoubi", meaning: "Sunday", indonesian: "Minggu", level: "N5", round: 13 },
    { kanji: "平日", kana: "へいじつ", romaji: "heijitsu", meaning: "weekday", indonesian: "hari kerja", level: "N3", round: 13 },
    { kanji: "週末", kana: "しゅうまつ", romaji: "shuumatsu", meaning: "weekend", indonesian: "akhir pekan", level: "N4", round: 13 },
    { kanji: "毎月", kana: "まいつき", romaji: "maitsuki", meaning: "every month", indonesian: "setiap bulan", level: "N5", round: 13 },

    // Round 14 — 20 related vocabulary items
    { kanji: "一緒", kana: "いっしょ", romaji: "issho", meaning: "together", indonesian: "bersama", level: "N5", round: 14 },
    { kanji: "一人", kana: "ひとり", romaji: "hitori", meaning: "one person; alone", indonesian: "one person; alone", level: "N5", round: 14 },
    { kanji: "二人", kana: "ふたり", romaji: "futari", meaning: "two people", indonesian: "two people", level: "N5", round: 14 },
    { kanji: "今年", kana: "ことし", romaji: "kotoshi", meaning: "this year", indonesian: "this year", level: "N5", round: 14 },
    { kanji: "来年", kana: "らいねん", romaji: "rainen", meaning: "next year", indonesian: "next year", level: "N5", round: 14 },
    { kanji: "用事", kana: "ようじ", romaji: "youji", meaning: "errand; business", indonesian: "errand; business", level: "N5", round: 14 },
    { kanji: "仕事", kana: "しごと", romaji: "shigoto", meaning: "job; work", indonesian: "pekerjaan", level: "N5", round: 14 },
    { kanji: "住所", kana: "じゅうしょ", romaji: "juusho", meaning: "address", indonesian: "alamat", level: "N5", round: 14 },
    { kanji: "名前", kana: "なまえ", romaji: "namae", meaning: "name", indonesian: "nama", level: "N5", round: 14 },
    { kanji: "電話番号", kana: "でんわばんごう", romaji: "denwa bangou", meaning: "telephone number", indonesian: "nomor telepon", level: "N5", round: 14 },
    { kanji: "誕生日", kana: "たんじょうび", romaji: "tanjoubi", meaning: "birthday", indonesian: "ulang tahun", level: "N5", round: 14 },
    { kanji: "年齢", kana: "ねんれい", romaji: "nenrei", meaning: "age", indonesian: "usia", level: "N3", round: 14 },
    { kanji: "一日", kana: "いちにち", romaji: "ichinichi", meaning: "one day; whole day", indonesian: "satu hari; sepanjang hari", level: "N5", round: 14 },
    { kanji: "二日", kana: "ふつか", romaji: "futsuka", meaning: "second day; two days", indonesian: "tanggal dua; dua hari", level: "N5", round: 14 },
    { kanji: "三日", kana: "みっか", romaji: "mikka", meaning: "third day; three days", indonesian: "tanggal tiga; tiga hari", level: "N5", round: 14 },
    { kanji: "四日", kana: "よっか", romaji: "yokka", meaning: "fourth day; four days", indonesian: "tanggal empat; empat hari", level: "N5", round: 14 },
    { kanji: "五日", kana: "いつか", romaji: "itsuka", meaning: "fifth day; five days", indonesian: "tanggal lima; lima hari", level: "N5", round: 14 },
    { kanji: "六日", kana: "むいか", romaji: "muika", meaning: "sixth day; six days", indonesian: "tanggal enam; enam hari", level: "N5", round: 14 },
    { kanji: "七日", kana: "なのか", romaji: "nanoka", meaning: "seventh day; seven days", indonesian: "tanggal tujuh; tujuh hari", level: "N5", round: 14 },
    { kanji: "八日", kana: "ようか", romaji: "youka", meaning: "eighth day; eight days", indonesian: "tanggal delapan; delapan hari", level: "N5", round: 14 },

    // Round 15 — 20 related vocabulary items
    { kanji: "大きい", kana: "おおきい", romaji: "ookii", meaning: "big", indonesian: "besar", level: "N5", round: 15 },
    { kanji: "小さい", kana: "ちいさい", romaji: "chiisai", meaning: "small", indonesian: "kecil", level: "N5", round: 15 },
    { kanji: "新しい", kana: "あたらしい", romaji: "atarashii", meaning: "new", indonesian: "baru", level: "N5", round: 15 },
    { kanji: "古い", kana: "ふるい", romaji: "furui", meaning: "old", indonesian: "tua; lama", level: "N5", round: 15 },
    { kanji: "高い", kana: "たかい", romaji: "takai", meaning: "expensive; tall", indonesian: "expensive; tall", level: "N5", round: 15 },
    { kanji: "安い", kana: "やすい", romaji: "yasui", meaning: "cheap", indonesian: "murah", level: "N5", round: 15 },
    { kanji: "若い", kana: "わかい", romaji: "wakai", meaning: "young", indonesian: "muda", level: "N5", round: 15 },
    { kanji: "悪い", kana: "わるい", romaji: "warui", meaning: "bad", indonesian: "buruk", level: "N5", round: 15 },
    { kanji: "元気", kana: "げんき", romaji: "genki", meaning: "healthy; energetic", indonesian: "healthy; energetic", level: "N5", round: 15 },
    { kanji: "便利", kana: "べんり", romaji: "benri", meaning: "convenient", indonesian: "convenient", level: "N5", round: 15 },
    { kanji: "低い", kana: "ひくい", romaji: "hikui", meaning: "low; short", indonesian: "rendah; pendek", level: "N5", round: 15 },
    { kanji: "太い", kana: "ふとい", romaji: "futoi", meaning: "thick; fat", indonesian: "tebal; gemuk", level: "N4", round: 15 },
    { kanji: "細い", kana: "ほそい", romaji: "hosoi", meaning: "thin; slender", indonesian: "tipis; ramping", level: "N4", round: 15 },
    { kanji: "広い", kana: "ひろい", romaji: "hiroi", meaning: "wide; spacious", indonesian: "luas", level: "N5", round: 15 },
    { kanji: "狭い", kana: "せまい", romaji: "semai", meaning: "narrow; cramped", indonesian: "sempit", level: "N4", round: 15 },
    { kanji: "良い", kana: "よい", romaji: "yoi", meaning: "good", indonesian: "baik", level: "N5", round: 15 },
    { kanji: "近い", kana: "ちかい", romaji: "chikai", meaning: "near", indonesian: "dekat", level: "N5", round: 15 },
    { kanji: "遠い", kana: "とおい", romaji: "tooi", meaning: "far", indonesian: "jauh", level: "N5", round: 15 },
    { kanji: "速い", kana: "はやい", romaji: "hayai", meaning: "fast", indonesian: "cepat", level: "N4", round: 15 },
    { kanji: "遅い", kana: "おそい", romaji: "osoi", meaning: "slow; late", indonesian: "lambat; terlambat", level: "N5", round: 15 },

    // Round 16 — 20 related vocabulary items
    { kanji: "寒い", kana: "さむい", romaji: "samui", meaning: "cold (weather)", indonesian: "cold (weather)", level: "N5", round: 16 },
    { kanji: "熱い", kana: "あつい", romaji: "atsui", meaning: "hot (object)", indonesian: "hot (object)", level: "N5", round: 16 },
    { kanji: "冷たい", kana: "つめたい", romaji: "tsumetai", meaning: "cold (touch)", indonesian: "cold (touch)", level: "N5", round: 16 },
    { kanji: "楽しい", kana: "たのしい", romaji: "tanoshii", meaning: "fun", indonesian: "fun", level: "N5", round: 16 },
    { kanji: "面白い", kana: "おもしろい", romaji: "omoshiroi", meaning: "interesting", indonesian: "interesting", level: "N5", round: 16 },
    { kanji: "有名", kana: "ゆうめい", romaji: "yuumei", meaning: "famous", indonesian: "famous", level: "N5", round: 16 },
    { kanji: "美しい", kana: "うつくしい", romaji: "utsukushii", meaning: "beautiful", indonesian: "indah", level: "N4", round: 16 },
    { kanji: "不便", kana: "ふべん", romaji: "fuben", meaning: "inconvenient", indonesian: "inconvenient", level: "N4", round: 16 },
    { kanji: "静か", kana: "しずか", romaji: "shizuka", meaning: "quiet", indonesian: "tenang", level: "N5", round: 16 },
    { kanji: "にぎやか", kana: "にぎやか", romaji: "nigiyaka", meaning: "lively", indonesian: "ramai", level: "N5", round: 16 },
    { kanji: "簡単", kana: "かんたん", romaji: "kantan", meaning: "easy; simple", indonesian: "mudah; sederhana", level: "N4", round: 16 },
    { kanji: "複雑", kana: "ふくざつ", romaji: "fukuzatsu", meaning: "complicated", indonesian: "rumit", level: "N3", round: 16 },
    { kanji: "安全", kana: "あんぜん", romaji: "anzen", meaning: "safe", indonesian: "aman", level: "N4", round: 16 },
    { kanji: "危険", kana: "きけん", romaji: "kiken", meaning: "dangerous", indonesian: "berbahaya", level: "N4", round: 16 },
    { kanji: "大切", kana: "たいせつ", romaji: "taisetsu", meaning: "important; precious", indonesian: "penting; berharga", level: "N4", round: 16 },
    { kanji: "特別", kana: "とくべつ", romaji: "tokubetsu", meaning: "special", indonesian: "khusus", level: "N4", round: 16 },
    { kanji: "自由", kana: "じゆう", romaji: "jiyuu", meaning: "free; freedom", indonesian: "bebas; kebebasan", level: "N3", round: 16 },
    { kanji: "十分", kana: "じゅうぶん", romaji: "juubun", meaning: "enough; sufficient", indonesian: "cukup", level: "N4", round: 16 },
    { kanji: "丁寧", kana: "ていねい", romaji: "teinei", meaning: "polite; careful", indonesian: "sopan; teliti", level: "N4", round: 16 },
    { kanji: "丈夫", kana: "じょうぶ", romaji: "joubu", meaning: "strong; durable", indonesian: "kuat; tahan lama", level: "N4", round: 16 },

    // Round 17 — 20 related vocabulary items
    { kanji: "忙しい", kana: "いそがしい", romaji: "isogashii", meaning: "busy", indonesian: "busy", level: "N5", round: 17 },
    { kanji: "大丈夫", kana: "だいじょうぶ", romaji: "daijoubu", meaning: "okay; all right", indonesian: "okay; all right", level: "N5", round: 17 },
    { kanji: "本当", kana: "ほんとう", romaji: "hontou", meaning: "true; really", indonesian: "benar; sungguh", level: "N5", round: 17 },
    { kanji: "全部", kana: "ぜんぶ", romaji: "zenbu", meaning: "all", indonesian: "semua", level: "N5", round: 17 },
    { kanji: "肉屋", kana: "にくや", romaji: "nikuya", meaning: "butcher", indonesian: "butcher", level: "N5", round: 17 },
    { kanji: "魚屋", kana: "さかなや", romaji: "sakanaya", meaning: "fish shop", indonesian: "fish shop", level: "N5", round: 17 },
    { kanji: "八百屋", kana: "やおや", romaji: "yaoya", meaning: "greengrocer", indonesian: "greengrocer", level: "N4", round: 17 },
    { kanji: "終わる", kana: "おわる", romaji: "owaru", meaning: "to finish", indonesian: "selesai; menyelesaikan", level: "N5", round: 17 },
    { kanji: "働く", kana: "はたらく", romaji: "hataraku", meaning: "to work", indonesian: "bekerja", level: "N5", round: 17 },
    { kanji: "気持ち", kana: "きもち", romaji: "kimochi", meaning: "feeling", indonesian: "perasaan", level: "N5", round: 17 },
    { kanji: "人気", kana: "にんき", romaji: "ninki", meaning: "popularity; popular", indonesian: "popularity; popular", level: "N4", round: 17 },
    { kanji: "喜ぶ", kana: "よろこぶ", romaji: "yorokobu", meaning: "to be delighted", indonesian: "bergembira", level: "N3", round: 17 },
    { kanji: "怒る", kana: "おこる", romaji: "okoru", meaning: "to get angry", indonesian: "marah", level: "N4", round: 17 },
    { kanji: "泣く", kana: "なく", romaji: "naku", meaning: "to cry", indonesian: "menangis", level: "N4", round: 17 },
    { kanji: "心配", kana: "しんぱい", romaji: "shinpai", meaning: "worry; concern", indonesian: "khawatir", level: "N4", round: 17 },
    { kanji: "安心", kana: "あんしん", romaji: "anshin", meaning: "relief; peace of mind", indonesian: "lega; tenang", level: "N3", round: 17 },
    { kanji: "緊張", kana: "きんちょう", romaji: "kinchou", meaning: "nervousness; tension", indonesian: "ketegangan; gugup", level: "N3", round: 17 },
    { kanji: "興味", kana: "きょうみ", romaji: "kyoumi", meaning: "interest", indonesian: "minat", level: "N3", round: 17 },
    { kanji: "幸せ", kana: "しあわせ", romaji: "shiawase", meaning: "happiness; happy", indonesian: "kebahagiaan; bahagia", level: "N3", round: 17 },
    { kanji: "寂しい", kana: "さびしい", romaji: "sabishii", meaning: "lonely", indonesian: "kesepian", level: "N4", round: 17 },

    // Round 18 — 20 related vocabulary items
    { kanji: "寄る", kana: "よる", romaji: "yoru", meaning: "to stop by; to drop in", indonesian: "mampir", level: "N4", round: 18 },
    { kanji: "親切", kana: "しんせつ", romaji: "shinsetsu", meaning: "kind; kind-hearted", indonesian: "baik hati", level: "N4", round: 18 },
    { kanji: "難しい", kana: "むずかしい", romaji: "muzukashii", meaning: "difficult", indonesian: "sulit", level: "N5", round: 18 },
    { kanji: "遠い", kana: "とおい", romaji: "tooi", meaning: "far; distant", indonesian: "jauh", level: "N5", round: 18 },
    { kanji: "運動", kana: "うんどう", romaji: "undou", meaning: "exercise; physical activity", indonesian: "olahraga; aktivitas fisik", level: "N5", round: 18 },
    { kanji: "今度", kana: "こんど", romaji: "kondo", meaning: "this time; next time", indonesian: "this time; next time", level: "N5", round: 18 },
    { kanji: "一昨日", kana: "おととい", romaji: "ototoi", meaning: "the day before yesterday", indonesian: "the day before yesterday", level: "N5", round: 18 },
    { kanji: "明後日", kana: "あさって", romaji: "asatte", meaning: "the day after tomorrow", indonesian: "the day after tomorrow", level: "N5", round: 18 },
    { kanji: "目的", kana: "もくてき", romaji: "mokuteki", meaning: "purpose; objective", indonesian: "tujuan", level: "N3", round: 18 },
    { kanji: "住民", kana: "じゅうみん", romaji: "juumin", meaning: "resident; inhabitant", indonesian: "penduduk", level: "N3", round: 18 },
    { kanji: "近所", kana: "きんじょ", romaji: "kinjo", meaning: "neighborhood", indonesian: "lingkungan sekitar", level: "N4", round: 18 },
    { kanji: "住所", kana: "じゅうしょ", romaji: "juusho", meaning: "address", indonesian: "alamat", level: "N5", round: 18 },
    { kanji: "住む", kana: "すむ", romaji: "sumu", meaning: "to live; reside", indonesian: "tinggal", level: "N5", round: 18 },
    { kanji: "引っ越す", kana: "ひっこす", romaji: "hikkosu", meaning: "to move house", indonesian: "pindah rumah", level: "N4", round: 18 },
    { kanji: "訪ねる", kana: "たずねる", romaji: "tazuneru", meaning: "to visit", indonesian: "mengunjungi", level: "N4", round: 18 },
    { kanji: "訪問", kana: "ほうもん", romaji: "houmon", meaning: "visit", indonesian: "kunjungan", level: "N3", round: 18 },
    { kanji: "目的地", kana: "もくてきち", romaji: "mokutekichi", meaning: "destination", indonesian: "tujuan perjalanan", level: "N3", round: 18 },
    { kanji: "距離", kana: "きょり", romaji: "kyori", meaning: "distance", indonesian: "jarak", level: "N3", round: 18 },
    { kanji: "地域", kana: "ちいき", romaji: "chiiki", meaning: "area; region", indonesian: "wilayah; daerah", level: "N3", round: 18 },
    { kanji: "市民", kana: "しみん", romaji: "shimin", meaning: "citizen", indonesian: "warga kota", level: "N3", round: 18 },

    // Round 19 — 20 related vocabulary items
    { kanji: "起きる", kana: "おきる", romaji: "okiru", meaning: "to wake up; get up", indonesian: "bangun", level: "N5", round: 19 },
    { kanji: "寝る", kana: "ねる", romaji: "neru", meaning: "to sleep; go to bed", indonesian: "tidur", level: "N5", round: 19 },
    { kanji: "洗う", kana: "あらう", romaji: "arau", meaning: "to wash", indonesian: "mencuci", level: "N5", round: 19 },
    { kanji: "着る", kana: "きる", romaji: "kiru", meaning: "to wear (upper body)", indonesian: "memakai", level: "N5", round: 19 },
    { kanji: "脱ぐ", kana: "ぬぐ", romaji: "nugu", meaning: "to take off clothes", indonesian: "melepas pakaian", level: "N5", round: 19 },
    { kanji: "作る", kana: "つくる", romaji: "tsukuru", meaning: "to make; create", indonesian: "membuat", level: "N5", round: 19 },
    { kanji: "使う", kana: "つかう", romaji: "tsukau", meaning: "to use", indonesian: "menggunakan", level: "N5", round: 19 },
    { kanji: "持つ", kana: "もつ", romaji: "motsu", meaning: "to hold; carry", indonesian: "memegang; membawa", level: "N5", round: 19 },
    { kanji: "待つ", kana: "まつ", romaji: "matsu", meaning: "to wait", indonesian: "menunggu", level: "N5", round: 19 },
    { kanji: "取る", kana: "とる", romaji: "toru", meaning: "to take; pick up", indonesian: "mengambil", level: "N5", round: 19 },
    { kanji: "置く", kana: "おく", romaji: "oku", meaning: "to put; place", indonesian: "meletakkan", level: "N5", round: 19 },
    { kanji: "呼ぶ", kana: "よぶ", romaji: "yobu", meaning: "to call; invite", indonesian: "memanggil; mengundang", level: "N5", round: 19 },
    { kanji: "会う", kana: "あう", romaji: "au", meaning: "to meet", indonesian: "bertemu", level: "N5", round: 19 },
    { kanji: "休む", kana: "やすむ", romaji: "yasumu", meaning: "to rest; take a day off", indonesian: "beristirahat; libur", level: "N5", round: 19 },
    { kanji: "出かける", kana: "でかける", romaji: "dekakeru", meaning: "to go out", indonesian: "keluar; bepergian", level: "N5", round: 19 },
    { kanji: "掃除する", kana: "そうじする", romaji: "souji suru", meaning: "to clean", indonesian: "membersihkan", level: "N5", round: 19 },
    { kanji: "料理する", kana: "りょうりする", romaji: "ryouri suru", meaning: "to cook", indonesian: "memasak", level: "N5", round: 19 },
    { kanji: "勉強する", kana: "べんきょうする", romaji: "benkyou suru", meaning: "to study", indonesian: "belajar", level: "N5", round: 19 },
    { kanji: "買い物", kana: "かいもの", romaji: "kaimono", meaning: "shopping", indonesian: "shopping", level: "N5", round: 19 },
    { kanji: "散歩", kana: "さんぽ", romaji: "sanpo", meaning: "walk; stroll", indonesian: "walk; stroll", level: "N5", round: 19 },

    // Round 20 — 20 related vocabulary items
    { kanji: "水", kana: "みず", romaji: "mizu", meaning: "water", indonesian: "air", level: "N5", round: 20 },
    { kanji: "お茶", kana: "おちゃ", romaji: "ocha", meaning: "tea", indonesian: "teh", level: "N5", round: 20 },
    { kanji: "ご飯", kana: "ごはん", romaji: "gohan", meaning: "rice; meal", indonesian: "nasi; makanan", level: "N5", round: 20 },
    { kanji: "肉", kana: "にく", romaji: "niku", meaning: "meat", indonesian: "daging", level: "N5", round: 20 },
    { kanji: "魚", kana: "さかな", romaji: "sakana", meaning: "fish", indonesian: "ikan", level: "N5", round: 20 },
    { kanji: "卵", kana: "たまご", romaji: "tamago", meaning: "egg", indonesian: "telur", level: "N5", round: 20 },
    { kanji: "牛乳", kana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "milk", indonesian: "susu", level: "N5", round: 20 },
    { kanji: "パン", kana: "パン", romaji: "pan", meaning: "bread", indonesian: "roti", level: "N5", round: 20 },
    { kanji: "昼ご飯", kana: "ひるごはん", romaji: "hirugohan", meaning: "lunch", indonesian: "makan siang", level: "N5", round: 20 },
    { kanji: "晩ご飯", kana: "ばんごはん", romaji: "bangohan", meaning: "dinner", indonesian: "makan malam", level: "N5", round: 20 },
    { kanji: "注文", kana: "ちゅうもん", romaji: "chuumon", meaning: "order (at a restaurant/shop)", indonesian: "order (at a restaurant/shop)", level: "N4", round: 20 },
    { kanji: "会計", kana: "かいけい", romaji: "kaikei", meaning: "bill; checkout; payment", indonesian: "bill; checkout; payment", level: "N4", round: 20 },
    { kanji: "お釣り", kana: "おつり", romaji: "otsuri", meaning: "change (money)", indonesian: "change (money)", level: "N4", round: 20 },
    { kanji: "袋", kana: "ふくろ", romaji: "fukuro", meaning: "bag; sack", indonesian: "kantong; karung", level: "N4", round: 20 },
    { kanji: "箸", kana: "はし", romaji: "hashi", meaning: "chopsticks", indonesian: "chopsticks", level: "N4", round: 20 },
    { kanji: "皿", kana: "さら", romaji: "sara", meaning: "plate; dish", indonesian: "plate; dish", level: "N4", round: 20 },
    { kanji: "美味しい", kana: "おいしい", romaji: "oishii", meaning: "delicious", indonesian: "delicious", level: "N5", round: 20 },
    { kanji: "甘い", kana: "あまい", romaji: "amai", meaning: "sweet", indonesian: "sweet", level: "N5", round: 20 },
    { kanji: "辛い", kana: "からい", romaji: "karai", meaning: "spicy", indonesian: "spicy", level: "N4", round: 20 },
    { kanji: "お腹", kana: "おなか", romaji: "onaka", meaning: "stomach; belly", indonesian: "stomach; belly", level: "N5", round: 20 },

    // Round 21 — 20 related vocabulary items
    { kanji: "駅", kana: "えき", romaji: "eki", meaning: "station", indonesian: "stasiun", level: "N5", round: 21 },
    { kanji: "道", kana: "みち", romaji: "michi", meaning: "road; way", indonesian: "jalan", level: "N5", round: 21 },
    { kanji: "右", kana: "みぎ", romaji: "migi", meaning: "right", indonesian: "kanan", level: "N5", round: 21 },
    { kanji: "左", kana: "ひだり", romaji: "hidari", meaning: "left", indonesian: "kiri", level: "N5", round: 21 },
    { kanji: "前", kana: "まえ", romaji: "mae", meaning: "front; before", indonesian: "depan; sebelum", level: "N5", round: 21 },
    { kanji: "後ろ", kana: "うしろ", romaji: "ushiro", meaning: "behind; back", indonesian: "belakang", level: "N5", round: 21 },
    { kanji: "近く", kana: "ちかく", romaji: "chikaku", meaning: "nearby; vicinity", indonesian: "dekat; sekitar", level: "N5", round: 21 },
    { kanji: "近い", kana: "ちかい", romaji: "chikai", meaning: "near; close", indonesian: "dekat", level: "N5", round: 21 },
    { kanji: "曲がる", kana: "まがる", romaji: "magaru", meaning: "to turn", indonesian: "berbelok", level: "N5", round: 21 },
    { kanji: "渡る", kana: "わたる", romaji: "wataru", meaning: "to cross", indonesian: "menyeberang", level: "N4", round: 21 },
    { kanji: "信号", kana: "しんごう", romaji: "shingou", meaning: "traffic light", indonesian: "lampu lalu lintas", level: "N4", round: 21 },
    { kanji: "交差点", kana: "こうさてん", romaji: "kousaten", meaning: "intersection", indonesian: "persimpangan", level: "N4", round: 21 },
    { kanji: "入口", kana: "いりぐち", romaji: "iriguchi", meaning: "entrance", indonesian: "pintu masuk", level: "N5", round: 21 },
    { kanji: "出口", kana: "でぐち", romaji: "deguchi", meaning: "exit", indonesian: "pintu keluar", level: "N5", round: 21 },
    { kanji: "切符", kana: "きっぷ", romaji: "kippu", meaning: "ticket", indonesian: "tiket", level: "N5", round: 21 },
    { kanji: "電車賃", kana: "でんしゃちん", romaji: "denshachin", meaning: "train fare", indonesian: "train fare", level: "N4", round: 21 },
    { kanji: "乗り換える", kana: "のりかえる", romaji: "norikaeru", meaning: "to transfer (trains/buses)", indonesian: "berganti kereta/bus", level: "N4", round: 21 },
    { kanji: "着く", kana: "つく", romaji: "tsuku", meaning: "to arrive", indonesian: "tiba", level: "N5", round: 21 },
    { kanji: "急ぐ", kana: "いそぐ", romaji: "isogu", meaning: "to hurry", indonesian: "bergegas", level: "N4", round: 21 },
    { kanji: "迷う", kana: "まよう", romaji: "mayou", meaning: "to get lost; be unsure", indonesian: "tersesat; ragu", level: "N4", round: 21 },

    // Round 22 — 20 related vocabulary items
    { kanji: "職場", kana: "しょくば", romaji: "shokuba", meaning: "workplace", indonesian: "tempat kerja", level: "N4", round: 22 },
    { kanji: "同僚", kana: "どうりょう", romaji: "douryou", meaning: "coworker; colleague", indonesian: "coworker; colleague", level: "N3", round: 22 },
    { kanji: "上司", kana: "じょうし", romaji: "joushi", meaning: "boss; supervisor", indonesian: "boss; supervisor", level: "N3", round: 22 },
    { kanji: "会議", kana: "かいぎ", romaji: "kaigi", meaning: "meeting", indonesian: "rapat", level: "N4", round: 22 },
    { kanji: "予定", kana: "よてい", romaji: "yotei", meaning: "plan; schedule", indonesian: "rencana; jadwal", level: "N4", round: 22 },
    { kanji: "連絡", kana: "れんらく", romaji: "renraku", meaning: "contact; communication", indonesian: "kontak; komunikasi", level: "N4", round: 22 },
    { kanji: "確認", kana: "かくにん", romaji: "kakunin", meaning: "confirmation; checking", indonesian: "konfirmasi; pemeriksaan", level: "N3", round: 22 },
    { kanji: "説明", kana: "せつめい", romaji: "setsumei", meaning: "explanation", indonesian: "penjelasan", level: "N4", round: 22 },
    { kanji: "問題", kana: "もんだい", romaji: "mondai", meaning: "problem; question", indonesian: "masalah; pertanyaan", level: "N4", round: 22 },
    { kanji: "必要", kana: "ひつよう", romaji: "hitsuyou", meaning: "necessary; needed", indonesian: "perlu; dibutuhkan", level: "N4", round: 22 },
    { kanji: "準備", kana: "じゅんび", romaji: "junbi", meaning: "preparation", indonesian: "persiapan", level: "N4", round: 22 },
    { kanji: "資料", kana: "しりょう", romaji: "shiryou", meaning: "materials; documents", indonesian: "materials; documents", level: "N3", round: 22 },
    { kanji: "メール", kana: "メール", romaji: "meeru", meaning: "email", indonesian: "email", level: "N5", round: 22 },
    { kanji: "送る", kana: "おくる", romaji: "okuru", meaning: "to send", indonesian: "mengirim", level: "N5", round: 22 },
    { kanji: "受け取る", kana: "うけとる", romaji: "uketoru", meaning: "to receive", indonesian: "menerima", level: "N4", round: 22 },
    { kanji: "間に合う", kana: "まにあう", romaji: "maniau", meaning: "to be in time", indonesian: "tepat waktu", level: "N4", round: 22 },
    { kanji: "遅れる", kana: "おくれる", romaji: "okureru", meaning: "to be late", indonesian: "terlambat", level: "N4", round: 22 },
    { kanji: "頑張る", kana: "がんばる", romaji: "ganbaru", meaning: "to do one’s best; work hard", indonesian: "berusaha sebaik mungkin", level: "N4", round: 22 },
    { kanji: "暇", kana: "ひま", romaji: "hima", meaning: "free time; not busy", indonesian: "free time; not busy", level: "N5", round: 22 },
    { kanji: "休憩", kana: "きゅうけい", romaji: "kyuukei", meaning: "break; rest", indonesian: "break; rest", level: "N4", round: 22 },

    // Round 23 — 20 related vocabulary items
    { kanji: "友達", kana: "ともだち", romaji: "tomodachi", meaning: "friend", indonesian: "teman", level: "N5", round: 23 },
    { kanji: "人", kana: "ひと", romaji: "hito", meaning: "person", indonesian: "orang", level: "N5", round: 23 },
    { kanji: "男", kana: "おとこ", romaji: "otoko", meaning: "man; male", indonesian: "pria; laki-laki", level: "N5", round: 23 },
    { kanji: "女", kana: "おんな", romaji: "onna", meaning: "woman; female", indonesian: "wanita; perempuan", level: "N5", round: 23 },
    { kanji: "好き", kana: "すき", romaji: "suki", meaning: "liked; favorite", indonesian: "suka; favorit", level: "N5", round: 23 },
    { kanji: "嫌い", kana: "きらい", romaji: "kirai", meaning: "disliked; hate", indonesian: "tidak suka; benci", level: "N5", round: 23 },
    { kanji: "嬉しい", kana: "うれしい", romaji: "ureshii", meaning: "happy; glad", indonesian: "senang; gembira", level: "N4", round: 23 },
    { kanji: "悲しい", kana: "かなしい", romaji: "kanashii", meaning: "sad", indonesian: "sedih", level: "N4", round: 23 },
    { kanji: "怖い", kana: "こわい", romaji: "kowai", meaning: "scary; afraid", indonesian: "menakutkan; takut", level: "N4", round: 23 },
    { kanji: "疲れる", kana: "つかれる", romaji: "tsukareru", meaning: "to get tired", indonesian: "menjadi lelah", level: "N4", round: 23 },
    { kanji: "笑う", kana: "わらう", romaji: "warau", meaning: "to laugh; smile", indonesian: "tertawa; tersenyum", level: "N4", round: 23 },
    { kanji: "分かる", kana: "わかる", romaji: "wakaru", meaning: "to understand", indonesian: "mengerti", level: "N5", round: 23 },
    { kanji: "知る", kana: "しる", romaji: "shiru", meaning: "to know; find out", indonesian: "mengetahui", level: "N5", round: 23 },
    { kanji: "思う", kana: "おもう", romaji: "omou", meaning: "to think; feel", indonesian: "berpikir; merasa", level: "N5", round: 23 },
    { kanji: "言う", kana: "いう", romaji: "iu", meaning: "to say", indonesian: "mengatakan", level: "N5", round: 23 },
    { kanji: "頼む", kana: "たのむ", romaji: "tanomu", meaning: "to ask; request", indonesian: "meminta", level: "N4", round: 23 },
    { kanji: "約束", kana: "やくそく", romaji: "yakusoku", meaning: "promise; appointment", indonesian: "promise; appointment", level: "N4", round: 23 },
    { kanji: "理由", kana: "りゆう", romaji: "riyuu", meaning: "reason", indonesian: "alasan", level: "N4", round: 23 },
    { kanji: "多分", kana: "たぶん", romaji: "tabun", meaning: "probably; maybe", indonesian: "mungkin", level: "N4", round: 23 },
    { kanji: "もちろん", kana: "もちろん", romaji: "mochiron", meaning: "of course", indonesian: "tentu saja", level: "N4", round: 23 },

    // Round 24 — 20 related vocabulary items
    { kanji: "鍵", kana: "かぎ", romaji: "kagi", meaning: "key", indonesian: "kunci", level: "N4", round: 24 },
    { kanji: "靴", kana: "くつ", romaji: "kutsu", meaning: "shoes", indonesian: "sepatu", level: "N5", round: 24 },
    { kanji: "服", kana: "ふく", romaji: "fuku", meaning: "clothes", indonesian: "pakaian", level: "N5", round: 24 },
    { kanji: "鞄", kana: "かばん", romaji: "kaban", meaning: "bag", indonesian: "tas", level: "N5", round: 24 },
    { kanji: "傘", kana: "かさ", romaji: "kasa", meaning: "umbrella", indonesian: "payung", level: "N5", round: 24 },
    { kanji: "冷蔵庫", kana: "れいぞうこ", romaji: "reizouko", meaning: "refrigerator", indonesian: "kulkas", level: "N4", round: 24 },
    { kanji: "洗濯機", kana: "せんたくき", romaji: "sentakuki", meaning: "washing machine", indonesian: "mesin cuci", level: "N4", round: 24 },
    { kanji: "電気", kana: "でんき", romaji: "denki", meaning: "electricity; light", indonesian: "listrik; lampu", level: "N5", round: 24 },
    { kanji: "風呂", kana: "ふろ", romaji: "furo", meaning: "bath", indonesian: "mandi; bak mandi", level: "N5", round: 24 },
    { kanji: "トイレ", kana: "トイレ", romaji: "toire", meaning: "toilet; restroom", indonesian: "toilet; restroom", level: "N5", round: 24 },
    { kanji: "洗濯", kana: "せんたく", romaji: "sentaku", meaning: "laundry; washing", indonesian: "cucian; mencuci", level: "N5", round: 24 },
    { kanji: "ゴミ", kana: "ゴミ", romaji: "gomi", meaning: "garbage; trash", indonesian: "sampah", level: "N5", round: 24 },
    { kanji: "捨てる", kana: "すてる", romaji: "suteru", meaning: "to throw away", indonesian: "membuang", level: "N4", round: 24 },
    { kanji: "片付ける", kana: "かたづける", romaji: "katazukeru", meaning: "to tidy up; put away", indonesian: "merapikan", level: "N4", round: 24 },
    { kanji: "電池", kana: "でんち", romaji: "denchi", meaning: "battery", indonesian: "baterai", level: "N4", round: 24 },
    { kanji: "充電", kana: "じゅうでん", romaji: "juuden", meaning: "charging (a device)", indonesian: "charging (a device)", level: "N3", round: 24 },
    { kanji: "携帯", kana: "けいたい", romaji: "keitai", meaning: "mobile phone", indonesian: "ponsel", level: "N4", round: 24 },
    { kanji: "箱", kana: "はこ", romaji: "hako", meaning: "box", indonesian: "kotak", level: "N5", round: 24 },
    { kanji: "紙", kana: "かみ", romaji: "kami", meaning: "paper", indonesian: "kertas", level: "N5", round: 24 },
    { kanji: "タオル", kana: "タオル", romaji: "taoru", meaning: "towel", indonesian: "handuk", level: "N5", round: 24 },

    // Round 25 — 20 related vocabulary items
    { kanji: "早い", kana: "はやい", romaji: "hayai", meaning: "early; fast", indonesian: "early; fast", level: "N5", round: 25 },
    { kanji: "遅い", kana: "おそい", romaji: "osoi", meaning: "late; slow", indonesian: "late; slow", level: "N5", round: 25 },
    { kanji: "長い", kana: "ながい", romaji: "nagai", meaning: "long", indonesian: "panjang", level: "N5", round: 25 },
    { kanji: "短い", kana: "みじかい", romaji: "mijikai", meaning: "short", indonesian: "pendek", level: "N5", round: 25 },
    { kanji: "重い", kana: "おもい", romaji: "omoi", meaning: "heavy", indonesian: "berat", level: "N5", round: 25 },
    { kanji: "軽い", kana: "かるい", romaji: "karui", meaning: "light (weight)", indonesian: "ringan", level: "N4", round: 25 },
    { kanji: "強い", kana: "つよい", romaji: "tsuyoi", meaning: "strong", indonesian: "kuat", level: "N5", round: 25 },
    { kanji: "弱い", kana: "よわい", romaji: "yowai", meaning: "weak", indonesian: "lemah", level: "N5", round: 25 },
    { kanji: "明るい", kana: "あかるい", romaji: "akarui", meaning: "bright; cheerful", indonesian: "bright; cheerful", level: "N5", round: 25 },
    { kanji: "暗い", kana: "くらい", romaji: "kurai", meaning: "dark; gloomy", indonesian: "dark; gloomy", level: "N5", round: 25 },
    { kanji: "きれい", kana: "きれい", romaji: "kirei", meaning: "clean; beautiful", indonesian: "clean; beautiful", level: "N5", round: 25 },
    { kanji: "汚い", kana: "きたない", romaji: "kitanai", meaning: "dirty", indonesian: "kotor", level: "N5", round: 25 },
    { kanji: "同じ", kana: "おなじ", romaji: "onaji", meaning: "same", indonesian: "sama", level: "N5", round: 25 },
    { kanji: "違う", kana: "ちがう", romaji: "chigau", meaning: "to differ; be wrong", indonesian: "berbeda; salah", level: "N4", round: 25 },
    { kanji: "少し", kana: "すこし", romaji: "sukoshi", meaning: "a little; a few", indonesian: "sedikit", level: "N5", round: 25 },
    { kanji: "たくさん", kana: "たくさん", romaji: "takusan", meaning: "many; a lot", indonesian: "banyak", level: "N5", round: 25 },
    { kanji: "もっと", kana: "もっと", romaji: "motto", meaning: "more", indonesian: "lebih", level: "N5", round: 25 },
    { kanji: "まだ", kana: "まだ", romaji: "mada", meaning: "still; not yet", indonesian: "masih; belum", level: "N5", round: 25 },
    { kanji: "もう", kana: "もう", romaji: "mou", meaning: "already; anymore", indonesian: "sudah; lagi", level: "N5", round: 25 },
    { kanji: "すぐ", kana: "すぐ", romaji: "sugu", meaning: "immediately; soon", indonesian: "segera", level: "N5", round: 25 },

    // Round 26 — 20 related vocabulary items
    { kanji: "言葉", kana: "ことば", romaji: "kotoba", meaning: "word; language", indonesian: "kata; bahasa", level: "N5", round: 26 },
    { kanji: "会話", kana: "かいわ", romaji: "kaiwa", meaning: "conversation", indonesian: "percakapan", level: "N4", round: 26 },
    { kanji: "電話", kana: "でんわ", romaji: "denwa", meaning: "telephone; phone call", indonesian: "telepon; panggilan telepon", level: "N5", round: 26 },
    { kanji: "伝言", kana: "でんごん", romaji: "dengon", meaning: "message", indonesian: "pesan", level: "N4", round: 26 },
    { kanji: "発言", kana: "はつげん", romaji: "hatsugen", meaning: "statement; remark", indonesian: "pernyataan; ucapan", level: "N3", round: 26 },
    { kanji: "言い方", kana: "いいかた", romaji: "iikata", meaning: "way of saying", indonesian: "cara mengatakan", level: "N4", round: 26 },
    { kanji: "話し方", kana: "はなしかた", romaji: "hanashikata", meaning: "way of speaking", indonesian: "cara berbicara", level: "N4", round: 26 },
    { kanji: "相談", kana: "そうだん", romaji: "soudan", meaning: "consultation; discussion", indonesian: "konsultasi; berdiskusi", level: "N4", round: 26 },
    { kanji: "説明", kana: "せつめい", romaji: "setsumei", meaning: "explanation", indonesian: "penjelasan", level: "N4", round: 26 },
    { kanji: "質問", kana: "しつもん", romaji: "shitsumon", meaning: "question", indonesian: "pertanyaan", level: "N5", round: 26 },
    { kanji: "返事", kana: "へんじ", romaji: "henji", meaning: "reply; response", indonesian: "jawaban; balasan", level: "N4", round: 26 },
    { kanji: "返答", kana: "へんとう", romaji: "hentou", meaning: "reply; answer", indonesian: "jawaban; tanggapan", level: "N3", round: 26 },
    { kanji: "報告", kana: "ほうこく", romaji: "houkoku", meaning: "report", indonesian: "laporan; melaporkan", level: "N3", round: 26 },
    { kanji: "連絡", kana: "れんらく", romaji: "renraku", meaning: "contact; communication", indonesian: "kontak; menghubungi", level: "N4", round: 26 },
    { kanji: "知らせる", kana: "しらせる", romaji: "shiraseru", meaning: "to inform; notify", indonesian: "memberi tahu", level: "N4", round: 26 },
    { kanji: "伝える", kana: "つたえる", romaji: "tsutaeru", meaning: "to convey; tell", indonesian: "menyampaikan", level: "N4", round: 26 },
    { kanji: "語る", kana: "かたる", romaji: "kataru", meaning: "to tell; narrate", indonesian: "menceritakan; menuturkan", level: "N3", round: 26 },
    { kanji: "読む", kana: "よむ", romaji: "yomu", meaning: "to read", indonesian: "membaca", level: "N5", round: 26 },
    { kanji: "書く", kana: "かく", romaji: "kaku", meaning: "to write", indonesian: "menulis", level: "N5", round: 26 },
    { kanji: "聞く", kana: "きく", romaji: "kiku", meaning: "to listen; ask", indonesian: "mendengar; bertanya", level: "N5", round: 26 },

    // Round 27 — 20 related vocabulary items
    { kanji: "手", kana: "て", romaji: "te", meaning: "hand", indonesian: "tangan", level: "N5", round: 27 },
    { kanji: "上手", kana: "じょうず", romaji: "jouzu", meaning: "skillful; good at", indonesian: "pandai; mahir", level: "N5", round: 27 },
    { kanji: "下手", kana: "へた", romaji: "heta", meaning: "unskillful; poor at", indonesian: "tidak pandai; kurang mahir", level: "N5", round: 27 },
    { kanji: "手紙", kana: "てがみ", romaji: "tegami", meaning: "letter", indonesian: "surat", level: "N5", round: 27 },
    { kanji: "切手", kana: "きって", romaji: "kitte", meaning: "postage stamp", indonesian: "perangko", level: "N5", round: 27 },
    { kanji: "手伝う", kana: "てつだう", romaji: "tetsudau", meaning: "to help", indonesian: "membantu", level: "N5", round: 27 },
    { kanji: "持つ", kana: "もつ", romaji: "motsu", meaning: "to hold; carry", indonesian: "memegang; membawa", level: "N5", round: 27 },
    { kanji: "取る", kana: "とる", romaji: "toru", meaning: "to take", indonesian: "mengambil", level: "N5", round: 27 },
    { kanji: "拾う", kana: "ひろう", romaji: "hirou", meaning: "to pick up", indonesian: "memungut", level: "N4", round: 27 },
    { kanji: "押す", kana: "おす", romaji: "osu", meaning: "to push; press", indonesian: "mendorong; menekan", level: "N5", round: 27 },
    { kanji: "引く", kana: "ひく", romaji: "hiku", meaning: "to pull", indonesian: "menarik", level: "N5", round: 27 },
    { kanji: "投げる", kana: "なげる", romaji: "nageru", meaning: "to throw", indonesian: "melempar", level: "N4", round: 27 },
    { kanji: "指", kana: "ゆび", romaji: "yubi", meaning: "finger", indonesian: "jari", level: "N4", round: 27 },
    { kanji: "指す", kana: "さす", romaji: "sasu", meaning: "to point", indonesian: "menunjuk", level: "N4", round: 27 },
    { kanji: "握る", kana: "にぎる", romaji: "nigiru", meaning: "to grasp; hold", indonesian: "menggenggam", level: "N3", round: 27 },
    { kanji: "打つ", kana: "うつ", romaji: "utsu", meaning: "to hit; strike", indonesian: "memukul", level: "N4", round: 27 },
    { kanji: "払う", kana: "はらう", romaji: "harau", meaning: "to pay", indonesian: "membayar", level: "N4", round: 27 },
    { kanji: "探す", kana: "さがす", romaji: "sagasu", meaning: "to search for", indonesian: "mencari", level: "N4", round: 27 },
    { kanji: "選ぶ", kana: "えらぶ", romaji: "erabu", meaning: "to choose", indonesian: "memilih", level: "N4", round: 27 },
    { kanji: "捨てる", kana: "すてる", romaji: "suteru", meaning: "to throw away", indonesian: "membuang", level: "N4", round: 27 },

    // Round 28 — 20 related vocabulary items
    { kanji: "心", kana: "こころ", romaji: "kokoro", meaning: "heart; mind", indonesian: "hati; pikiran", level: "N4", round: 28 },
    { kanji: "安心", kana: "あんしん", romaji: "anshin", meaning: "relief; peace of mind", indonesian: "lega; tenang", level: "N4", round: 28 },
    { kanji: "心配", kana: "しんぱい", romaji: "shinpai", meaning: "worry; concern", indonesian: "khawatir; kekhawatiran", level: "N4", round: 28 },
    { kanji: "気持ち", kana: "きもち", romaji: "kimochi", meaning: "feeling", indonesian: "perasaan", level: "N5", round: 28 },
    { kanji: "気分", kana: "きぶん", romaji: "kibun", meaning: "mood; feeling", indonesian: "suasana hati; perasaan", level: "N4", round: 28 },
    { kanji: "元気", kana: "げんき", romaji: "genki", meaning: "healthy; energetic", indonesian: "sehat; bersemangat", level: "N5", round: 28 },
    { kanji: "本気", kana: "ほんき", romaji: "honki", meaning: "seriousness; earnestness", indonesian: "kesungguhan; serius", level: "N3", round: 28 },
    { kanji: "勇気", kana: "ゆうき", romaji: "yuuki", meaning: "courage", indonesian: "keberanian", level: "N3", round: 28 },
    { kanji: "嬉しい", kana: "うれしい", romaji: "ureshii", meaning: "happy; glad", indonesian: "senang; gembira", level: "N4", round: 28 },
    { kanji: "悲しい", kana: "かなしい", romaji: "kanashii", meaning: "sad", indonesian: "sedih", level: "N4", round: 28 },
    { kanji: "怖い", kana: "こわい", romaji: "kowai", meaning: "scary; afraid", indonesian: "menakutkan; takut", level: "N4", round: 28 },
    { kanji: "怒る", kana: "おこる", romaji: "okoru", meaning: "to get angry", indonesian: "marah", level: "N4", round: 28 },
    { kanji: "喜ぶ", kana: "よろこぶ", romaji: "yorokobu", meaning: "to be delighted", indonesian: "bergembira", level: "N3", round: 28 },
    { kanji: "笑う", kana: "わらう", romaji: "warau", meaning: "to laugh; smile", indonesian: "tertawa; tersenyum", level: "N4", round: 28 },
    { kanji: "泣く", kana: "なく", romaji: "naku", meaning: "to cry", indonesian: "menangis", level: "N4", round: 28 },
    { kanji: "思う", kana: "おもう", romaji: "omou", meaning: "to think; feel", indonesian: "berpikir; merasa", level: "N5", round: 28 },
    { kanji: "考える", kana: "かんがえる", romaji: "kangaeru", meaning: "to think; consider", indonesian: "berpikir; mempertimbangkan", level: "N5", round: 28 },
    { kanji: "忘れる", kana: "わすれる", romaji: "wasureru", meaning: "to forget", indonesian: "lupa; melupakan", level: "N5", round: 28 },
    { kanji: "覚える", kana: "おぼえる", romaji: "oboeru", meaning: "to remember; memorize", indonesian: "mengingat; menghafal", level: "N5", round: 28 },
    { kanji: "感じる", kana: "かんじる", romaji: "kanjiru", meaning: "to feel; sense", indonesian: "merasakan", level: "N3", round: 28 },

    // Round 29 — 20 related vocabulary items
    { kanji: "日", kana: "ひ", romaji: "hi", meaning: "day; sun", indonesian: "hari; matahari", level: "N5", round: 29 },
    { kanji: "毎日", kana: "まいにち", romaji: "mainichi", meaning: "every day", indonesian: "setiap hari", level: "N5", round: 29 },
    { kanji: "平日", kana: "へいじつ", romaji: "heijitsu", meaning: "weekday", indonesian: "hari kerja", level: "N4", round: 29 },
    { kanji: "休日", kana: "きゅうじつ", romaji: "kyuujitsu", meaning: "holiday; day off", indonesian: "hari libur", level: "N4", round: 29 },
    { kanji: "曜日", kana: "ようび", romaji: "youbi", meaning: "day of the week", indonesian: "hari dalam minggu", level: "N5", round: 29 },
    { kanji: "月曜日", kana: "げつようび", romaji: "getsuyoubi", meaning: "Monday", indonesian: "Senin", level: "N5", round: 29 },
    { kanji: "火曜日", kana: "かようび", romaji: "kayoubi", meaning: "Tuesday", indonesian: "Selasa", level: "N5", round: 29 },
    { kanji: "水曜日", kana: "すいようび", romaji: "suiyoubi", meaning: "Wednesday", indonesian: "Rabu", level: "N5", round: 29 },
    { kanji: "木曜日", kana: "もくようび", romaji: "mokuyoubi", meaning: "Thursday", indonesian: "Kamis", level: "N5", round: 29 },
    { kanji: "金曜日", kana: "きんようび", romaji: "kinyoubi", meaning: "Friday", indonesian: "Jumat", level: "N5", round: 29 },
    { kanji: "土曜日", kana: "どようび", romaji: "doyoubi", meaning: "Saturday", indonesian: "Sabtu", level: "N5", round: 29 },
    { kanji: "日曜日", kana: "にちようび", romaji: "nichiyoubi", meaning: "Sunday", indonesian: "Minggu", level: "N5", round: 29 },
    { kanji: "日時", kana: "にちじ", romaji: "nichiji", meaning: "date and time", indonesian: "tanggal dan waktu", level: "N3", round: 29 },
    { kanji: "日記", kana: "にっき", romaji: "nikki", meaning: "diary", indonesian: "buku harian", level: "N4", round: 29 },
    { kanji: "予定日", kana: "よていび", romaji: "yoteibi", meaning: "scheduled date", indonesian: "tanggal yang dijadwalkan", level: "N3", round: 29 },
    { kanji: "今日", kana: "きょう", romaji: "kyou", meaning: "today", indonesian: "hari ini", level: "N5", round: 29 },
    { kanji: "昨日", kana: "きのう", romaji: "kinou", meaning: "yesterday", indonesian: "kemarin", level: "N5", round: 29 },
    { kanji: "明日", kana: "あした", romaji: "ashita", meaning: "tomorrow", indonesian: "besok", level: "N5", round: 29 },
    { kanji: "一昨日", kana: "おととい", romaji: "ototoi", meaning: "day before yesterday", indonesian: "kemarin lusa", level: "N5", round: 29 },
    { kanji: "明後日", kana: "あさって", romaji: "asatte", meaning: "day after tomorrow", indonesian: "lusa", level: "N5", round: 29 },

    // Round 30 — 20 related vocabulary items
    { kanji: "水", kana: "みず", romaji: "mizu", meaning: "water", indonesian: "air", level: "N5", round: 30 },
    { kanji: "飲み水", kana: "のみみず", romaji: "nomimizu", meaning: "drinking water", indonesian: "air minum", level: "N4", round: 30 },
    { kanji: "水道", kana: "すいどう", romaji: "suidou", meaning: "water supply; tap water", indonesian: "saluran air; air ledeng", level: "N4", round: 30 },
    { kanji: "お湯", kana: "おゆ", romaji: "oyu", meaning: "hot water", indonesian: "air panas", level: "N5", round: 30 },
    { kanji: "海", kana: "うみ", romaji: "umi", meaning: "sea", indonesian: "laut", level: "N5", round: 30 },
    { kanji: "川", kana: "かわ", romaji: "kawa", meaning: "river", indonesian: "sungai", level: "N5", round: 30 },
    { kanji: "池", kana: "いけ", romaji: "ike", meaning: "pond", indonesian: "kolam", level: "N4", round: 30 },
    { kanji: "泳ぐ", kana: "およぐ", romaji: "oyogu", meaning: "to swim", indonesian: "berenang", level: "N5", round: 30 },
    { kanji: "洗う", kana: "あらう", romaji: "arau", meaning: "to wash", indonesian: "mencuci", level: "N5", round: 30 },
    { kanji: "洗濯", kana: "せんたく", romaji: "sentaku", meaning: "laundry; washing", indonesian: "mencuci pakaian; cucian", level: "N5", round: 30 },
    { kanji: "洗面所", kana: "せんめんじょ", romaji: "senmenjo", meaning: "washroom; washbasin area", indonesian: "tempat cuci muka; wastafel", level: "N4", round: 30 },
    { kanji: "流す", kana: "ながす", romaji: "nagasu", meaning: "to let flow; flush", indonesian: "mengalirkan; menyiram", level: "N4", round: 30 },
    { kanji: "流れる", kana: "ながれる", romaji: "nagareru", meaning: "to flow", indonesian: "mengalir", level: "N4", round: 30 },
    { kanji: "涙", kana: "なみだ", romaji: "namida", meaning: "tears", indonesian: "air mata", level: "N3", round: 30 },
    { kanji: "汗", kana: "あせ", romaji: "ase", meaning: "sweat", indonesian: "keringat", level: "N3", round: 30 },
    { kanji: "濡れる", kana: "ぬれる", romaji: "nureru", meaning: "to get wet", indonesian: "menjadi basah", level: "N3", round: 30 },
    { kanji: "乾く", kana: "かわく", romaji: "kawaku", meaning: "to dry", indonesian: "menjadi kering", level: "N3", round: 30 },
    { kanji: "冷水", kana: "れいすい", romaji: "reisui", meaning: "cold water", indonesian: "air dingin", level: "N3", round: 30 },
    { kanji: "温水", kana: "おんすい", romaji: "onsui", meaning: "warm water", indonesian: "air hangat", level: "N3", round: 30 },
    { kanji: "水分", kana: "すいぶん", romaji: "suibun", meaning: "moisture; fluids", indonesian: "cairan; kadar air", level: "N3", round: 30 },
];
