export type Kanji = {
  kanji: string;
  kana: string;
  romaji: string;
  meaning: string;
  level: "N5"|"N4"|"N3"|"N2"|"N1";
  round?: number;
};

export type HardKanji = {
  kanji: string;
  wrongCount: number;
};

export function resetRemedy(){
  localStorage.removeItem('hard_kanji');
  alert('Kanji remedy reset successfully.')
}

// export const n5kanji_vocabularies: Kanji[] =[
export const n5Kanji_2: Kanji[] =[
  // School
  { kanji: "学校", kana: "がっこう", romaji: "gakkou", meaning: "school", level: "N5" },
  { kanji: "学生", kana: "がくせい", romaji: "gakusei", meaning: "student", level: "N5" },
  { kanji: "先生", kana: "せんせい", romaji: "sensei", meaning: "teacher", level: "N5" },
  { kanji: "大学", kana: "だいがく", romaji: "daigaku", meaning: "university", level: "N5" },
  { kanji: "高校", kana: "こうこう", romaji: "koukou", meaning: "high school", level: "N5" },
  { kanji: "教室", kana: "きょうしつ", romaji: "kyoushitsu", meaning: "classroom", level: "N5" },
  { kanji: "図書館", kana: "としょかん", romaji: "toshokan", meaning: "library", level: "N5" },
  { kanji: "教科書", kana: "きょうかしょ", romaji: "kyoukasho", meaning: "textbook", level: "N5" },
  { kanji: "辞書", kana: "じしょ", romaji: "jisho", meaning: "dictionary", level: "N5" },
  { kanji: "宿題", kana: "しゅくだい", romaji: "shukudai", meaning: "homework", level: "N5" },

  // Time
  { kanji: "今日", kana: "きょう", romaji: "kyou", meaning: "today", level: "N5" },
  { kanji: "昨日", kana: "きのう", romaji: "kinou", meaning: "yesterday", level: "N5" },
  { kanji: "明日", kana: "あした", romaji: "ashita", meaning: "tomorrow", level: "N5" },
  { kanji: "毎日", kana: "まいにち", romaji: "mainichi", meaning: "every day", level: "N5" },
  { kanji: "毎週", kana: "まいしゅう", romaji: "maishuu", meaning: "every week", level: "N5" },
  { kanji: "毎月", kana: "まいつき", romaji: "maitsuki", meaning: "every month", level: "N5" },
  { kanji: "毎年", kana: "まいとし", romaji: "maitoshi", meaning: "every year", level: "N5" },
  { kanji: "時間", kana: "じかん", romaji: "jikan", meaning: "time", level: "N5" },
  { kanji: "時計", kana: "とけい", romaji: "tokei", meaning: "clock", level: "N5" },

  // Places
  { kanji: "会社", kana: "かいしゃ", romaji: "kaisha", meaning: "company", level: "N5" },
  { kanji: "病院", kana: "びょういん", romaji: "byouin", meaning: "hospital", level: "N5" },
  { kanji: "銀行", kana: "ぎんこう", romaji: "ginkou", meaning: "bank", level: "N5" },
  { kanji: "郵便局", kana: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "post office", level: "N5" },
  { kanji: "駅前", kana: "えきまえ", romaji: "ekimae", meaning: "in front of the station", level: "N5" },
  { kanji: "入口", kana: "いりぐち", romaji: "iriguchi", meaning: "entrance", level: "N5" },
  { kanji: "出口", kana: "でぐち", romaji: "deguchi", meaning: "exit", level: "N5" },

  // Nationality
  { kanji: "日本", kana: "にほん", romaji: "nihon", meaning: "Japan", level: "N5" },
  { kanji: "日本人", kana: "にほんじん", romaji: "nihonjin", meaning: "Japanese person", level: "N5" },
  { kanji: "外国", kana: "がいこく", romaji: "gaikoku", meaning: "foreign country", level: "N5" },
  { kanji: "外国人", kana: "がいこくじん", romaji: "gaikokujin", meaning: "foreigner", level: "N5" },

  // Transportation
  { kanji: "電車", kana: "でんしゃ", romaji: "densha", meaning: "train", level: "N5" },
  { kanji: "地下鉄", kana: "ちかてつ", romaji: "chikatetsu", meaning: "subway", level: "N5" },
  { kanji: "自転車", kana: "じてんしゃ", romaji: "jitensha", meaning: "bicycle", level: "N5" },
  { kanji: "空港", kana: "くうこう", romaji: "kuukou", meaning: "airport", level: "N5" },
  { kanji: "切符", kana: "きっぷ", romaji: "kippu", meaning: "ticket", level: "N5" },

  // Home & Family
  { kanji: "家族", kana: "かぞく", romaji: "kazoku", meaning: "family", level: "N5" },
  { kanji: "両親", kana: "りょうしん", romaji: "ryoushin", meaning: "parents", level: "N5" },
  { kanji: "兄弟", kana: "きょうだい", romaji: "kyoudai", meaning: "siblings", level: "N5" },
  { kanji: "台所", kana: "だいどころ", romaji: "daidokoro", meaning: "kitchen", level: "N5" },
  { kanji: "居間", kana: "いま", romaji: "ima", meaning: "living room", level: "N5" },

  // Daily Life
  { kanji: "朝食", kana: "ちょうしょく", romaji: "choushoku", meaning: "breakfast", level: "N5" },
  { kanji: "昼食", kana: "ちゅうしょく", romaji: "chuushoku", meaning: "lunch", level: "N5" },
  { kanji: "夕食", kana: "ゆうしょく", romaji: "yuushoku", meaning: "dinner", level: "N5" },
  { kanji: "飲み物", kana: "のみもの", romaji: "nomimono", meaning: "drink", level: "N5" },
  { kanji: "買い物", kana: "かいもの", romaji: "kaimono", meaning: "shopping", level: "N5" },

  // Nature & Weather
  { kanji: "天気", kana: "てんき", romaji: "tenki", meaning: "weather", level: "N5" },
  { kanji: "青空", kana: "あおぞら", romaji: "aozora", meaning: "blue sky", level: "N5" },
  { kanji: "雨天", kana: "うてん", romaji: "uten", meaning: "rainy weather", level: "N4" },
  { kanji: "雪国", kana: "ゆきぐに", romaji: "yukiguni", meaning: "snowy country", level: "N4" },

  // Work
  { kanji: "仕事", kana: "しごと", romaji: "shigoto", meaning: "work", level: "N5" },
  { kanji: "会議", kana: "かいぎ", romaji: "kaigi", meaning: "meeting", level: "N4" },
  { kanji: "社員", kana: "しゃいん", romaji: "shain", meaning: "company employee", level: "N4" },
  { kanji: "社長", kana: "しゃちょう", romaji: "shachou", meaning: "company president", level: "N4" },
  { kanji: "残業", kana: "ざんぎょう", romaji: "zangyou", meaning: "overtime", level: "N4" },
  { kanji: "報告", kana: "ほうこく", romaji: "houkoku", meaning: "report", level: "N4" },
  { kanji: "連絡", kana: "れんらく", romaji: "renraku", meaning: "contact; to call", level: "N4" },

  // Study
  { kanji: "勉強", kana: "べんきょう", romaji: "benkyou", meaning: "study", level: "N5" },
  { kanji: "試験", kana: "しけん", romaji: "shiken", meaning: "exam", level: "N4" },
  { kanji: "問題", kana: "もんだい", romaji: "mondai", meaning: "problem; question", level: "N4" },
  { kanji: "質問", kana: "しつもん", romaji: "shitsumon", meaning: "question", level: "N4" },
  { kanji: "答え", kana: "こたえ", romaji: "kotae", meaning: "answer", level: "N5" },
  { kanji: "復習", kana: "ふくしゅう", romaji: "fukushuu", meaning: "review", level: "N4" },
  { kanji: "練習", kana: "れんしゅう", romaji: "renshuu", meaning: "practice", level: "N4" },

  // City
  { kanji: "公園", kana: "こうえん", romaji: "kouen", meaning: "park", level: "N5" },
  { kanji: "交番", kana: "こうばん", romaji: "kouban", meaning: "police box", level: "N5" },
  { kanji: "道路", kana: "どうろ", romaji: "douro", meaning: "road", level: "N4" },
  { kanji: "歩道", kana: "ほどう", romaji: "hodou", meaning: "sidewalk", level: "N4" },
  { kanji: "信号", kana: "しんごう", romaji: "shingou", meaning: "traffic light", level: "N4" },

  // Shopping
  { kanji: "商品", kana: "しょうひん", romaji: "shouhin", meaning: "product", level: "N4" },
  { kanji: "料金", kana: "りょうきん", romaji: "ryoukin", meaning: "fee", level: "N4" },
  { kanji: "値段", kana: "ねだん", romaji: "nedan", meaning: "price", level: "N5" },
  { kanji: "売場", kana: "うりば", romaji: "uriba", meaning: "sales floor", level: "N4" },

  // Body & Health
  { kanji: "気分", kana: "きぶん", romaji: "kibun", meaning: "feeling; mood", level: "N4" },
  { kanji: "病気", kana: "びょうき", romaji: "byouki", meaning: "illness", level: "N5" },
  { kanji: "薬局", kana: "やっきょく", romaji: "yakkyoku", meaning: "pharmacy", level: "N4" },

  // Common Abstract Words
  { kanji: "意味", kana: "いみ", romaji: "imi", meaning: "meaning", level: "N4" },
  { kanji: "理由", kana: "りゆう", romaji: "riyuu", meaning: "reason", level: "N4" },
  { kanji: "予定", kana: "よてい", romaji: "yotei", meaning: "plan", level: "N4" },
  { kanji: "必要", kana: "ひつよう", romaji: "hitsuyou", meaning: "necessary", level: "N4" },
  { kanji: "大切", kana: "たいせつ", romaji: "taisetsu", meaning: "important", level: "N4" },
  { kanji: "安心", kana: "あんしん", romaji: "anshin", meaning: "relief; peace of mind", level: "N4" },
  { kanji: "心配", kana: "しんぱい", romaji: "shinpai", meaning: "worry", level: "N4" },
  { kanji: "興味", kana: "きょうみ", romaji: "kyoumi", meaning: "interest", level: "N4" },

  { kanji: "男子", kana: "だんし", romaji: "danshi", meaning: "Men's (room)", level: "N5" },
  { kanji: "女子", kana: "じょし", romaji: "joshi", meaning: "Women's (room)", level: "N5" },
  { kanji: "非常口", kana: "ひじょうぐち", romaji: "hijouguchi", meaning: "Emergency Exit", level: "N5" },
  { kanji: "自己紹介", kana: "じこしょうかい", romaji: "jikoshoukai", meaning: "self introduction", level: "N5" },

  { kanji: "面接", kana: "めんせつ", romaji: "mensetsu", meaning: "interview", level: "N5" },
  { kanji: "改札", kana: "かいさつ", romaji: "kaisatsu", meaning: "Ticket Gate", level: "N5" },
  { kanji: "新幹線", kana: "しんかんせん", romaji: "shinkansen", meaning: "Bullet Train", level: "N5" },
  { kanji: "普通", kana: "ふつう", romaji: "futsuu", meaning: "Local train", level: "N5" },
  { kanji: "営業中", kana: "えいぎょうちゅう", romaji: "eigyouchuu", meaning: "Open (business", level: "N4" },
  { kanji: "閉店", kana: "へいてん", romaji: "heiten", meaning: "Close (business)", level: "N4" },
  { kanji: "経営", kana: "けいえい", romaji: "keiei", meaning: "to run; own (business)", level: "N4" },
  
  { kanji: "子供", kana: "こども", romaji: "kodomo", meaning: "child", level: "N5" },
  { kanji: "洗濯", kana: "せんたく", romaji: "sentaku", meaning: "laundry", level: "N4" },
  { kanji: "受付", kana: "うけつけ", romaji: "uketsuke", meaning: "reception", level: "N4" },
  { kanji: "書類", kana: "しょるい", romaji: "shorui", meaning: "documents", level: "N4" },
  { kanji: "資料", kana: "しりょう", romaji: "shiryou", meaning: "materials; documents", level: "N4" },
  { kanji: "出勤", kana: "しゅっきん", romaji: "shukkin", meaning: "go to work", level: "N4" },
  { kanji: "退勤", kana: "たいきん", romaji: "taikin", meaning: "leave work", level: "N4" },
  { kanji: "注意", kana: "ちゅうい", romaji: "chuui", meaning: "caution", level: "N4" },
  { kanji: "危険", kana: "きけん", romaji: "kiken", meaning: "danger", level: "N4" },

  { kanji: "受付", kana: "うけつけ", romaji: "uketsuke", meaning: "reception", level: "N4" },
  { kanji: "書類", kana: "しょるい", romaji: "shorui", meaning: "documents", level: "N4" },
  { kanji: "資料", kana: "しりょう", romaji: "shiryou", meaning: "materials; documents", level: "N4" },

  { kanji: "世界", kana: "せかい", romaji: "sekai", meaning: "world", level: "N5" },
  { kanji: "文化", kana: "ぶんか", romaji: "bunka", meaning: "culture", level: "N4" },
  { kanji: "生活", kana: "せいかつ", romaji: "seikatsu", meaning: "daily life", level: "N4" },
  { kanji: "季節", kana: "きせつ", romaji: "kisetsu", meaning: "season", level: "N4" },
  { kanji: "自然", kana: "しぜん", romaji: "shizen", meaning: "nature", level: "N5" },
  { kanji: "忘れ", kana: "わすれ", romaji: "wasure", meaning: "to forget", level: "N5" },
  { kanji: "文法", kana: "ぶんぽう", romaji: "bunpo", meaning: "grammar", level: "N5" },
  { kanji: "お風呂", kana: "おふろ", romaji: "ofuro", meaning: "bath", level: "N5" },
  { kanji: "貸し", kana: "かし", romaji: "kashi", meaning: "to lend", level: "N5" },
  { kanji: "返し", kana: "かえし", romaji: "kaeshi", meaning: "to return", level: "N5" },
  { kanji: "寝る", kana: "ねる", romaji: "neru", meaning: "to sleep", level: "N5" },
  { kanji: "面白", kana: "おもしろ", romaji: "omoshiro", meaning: "interesting", level: "N5" },
  { kanji: "財布", kana: "さいふ", romaji: "saifu", meaning: "wallet", level: "N5" },
  { kanji: "忙しい", kana: "いそがしい", romaji: "isogashi", meaning: "busy", level: "N5" },
  { kanji: "美味しい", kana: "おいしい", romaji: "oishi", meaning: "delicious", level: "N4" }
]

export const n5Kanji_base: Kanji[] = [
  { kanji: "心", kana: "こころ", romaji: "kokoro", meaning: "heart; mind", level: "N4" },
  { kanji: "顔", kana: "かお", romaji: "kao", meaning: "face", level: "N4" },
  { kanji: "首", kana: "くび", romaji: "kubi", meaning: "neck", level: "N4" },
  { kanji: "頭", kana: "あたま", romaji: "atama", meaning: "head", level: "N4" },
  { kanji: "体", kana: "からだ", romaji: "karada", meaning: "body", level: "N5" },
  { kanji: "雨", kana: "あめ", romaji: "ame", meaning: "rain", level: "N5" },
  { kanji: "雪", kana: "ゆき", romaji: "yuki", meaning: "snow", level: "N5" },
  { kanji: "空", kana: "そら", romaji: "sora", meaning: "sky", level: "N5" },
  { kanji: "花", kana: "はな", romaji: "hana", meaning: "flower", level: "N5" },
  { kanji: "草", kana: "くさ", romaji: "kusa", meaning: "grass", level: "N4" },
  { kanji: "石", kana: "いし", romaji: "ishi", meaning: "stone", level: "N5" },
  { kanji: "家", kana: "いえ", romaji: "ie", meaning: "house", level: "N5" },
  { kanji: "店", kana: "みせ", romaji: "mise", meaning: "shop", level: "N5" },
  { kanji: "駅", kana: "えき", romaji: "eki", meaning: "station", level: "N5" },
  { kanji: "道", kana: "みち", romaji: "michi", meaning: "road; way", level: "N5" },
  { kanji: "場", kana: "ば", romaji: "ba", meaning: "place", level: "N4" },
  { kanji: "社", kana: "しゃ", romaji: "sha", meaning: "company; shrine", level: "N5" },
  { kanji: "員", kana: "いん", romaji: "in", meaning: "member", level: "N4" },
  { kanji: "工", kana: "こう", romaji: "kou", meaning: "craft; construction", level: "N5" },
  { kanji: "業", kana: "ぎょう", romaji: "gyou", meaning: "business; industry", level: "N4" },
  { kanji: "事", kana: "こと", romaji: "koto", meaning: "matter; thing", level: "N5" },
  { kanji: "文", kana: "ぶん", romaji: "bun", meaning: "writing; sentence", level: "N5" },
  { kanji: "字", kana: "じ", romaji: "ji", meaning: "character", level: "N5" },
  { kanji: "語", kana: "ご", romaji: "go", meaning: "language; word", level: "N5" },
  { kanji: "教", kana: "おし", romaji: "oshi", meaning: "teach", level: "N5" },
  { kanji: "習", kana: "なら", romaji: "nara", meaning: "learn; practice", level: "N4" },
  { kanji: "車", kana: "くるま", romaji: "kuruma", meaning: "vehicle", level: "N5" },
  { kanji: "電", kana: "でん", romaji: "den", meaning: "electricity", level: "N5" },
  { kanji: "気", kana: "き", romaji: "ki", meaning: "spirit; energy", level: "N5" },
  { kanji: "料", kana: "りょう", romaji: "ryou", meaning: "materials; fee", level: "N4" },
  { kanji: "理", kana: "り", romaji: "ri", meaning: "logic; reason", level: "N4" },
  { kanji: "経", kana: "けい", romaji: "kei", meaning: "manage; pass through", level: "N4" },
  { kanji: "営", kana: "えい", romaji: "ei", meaning: "operate", level: "N4" },
  { kanji: "開", kana: "ひら", romaji: "hira", meaning: "open", level: "N5" },
  { kanji: "閉", kana: "し", romaji: "shi", meaning: "close", level: "N4" },
  { kanji: "新", kana: "あたら", romaji: "atara", meaning: "new", level: "N5" },
  { kanji: "古", kana: "ふる", romaji: "furu", meaning: "old", level: "N5" },
  { kanji: "長", kana: "なが", romaji: "naga", meaning: "long; leader", level: "N5" },
  { kanji: "高", kana: "たか", romaji: "taka", meaning: "high; expensive", level: "N5" },
  { kanji: "安", kana: "やす", romaji: "yasu", meaning: "cheap; peaceful", level: "N5" },
  { kanji: "多", kana: "おお", romaji: "oo", meaning: "many", level: "N5" },
  { kanji: "少", kana: "すく", romaji: "suku", meaning: "few", level: "N5" },
  { kanji: "週", kana: "しゅう", romaji: "shuu", meaning: "week", level: "N5" },
  { kanji: "曜", kana: "よう", romaji: "you", meaning: "weekday", level: "N5" },
  { kanji: "午", kana: "ご", romaji: "go", meaning: "noon", level: "N5" },
  { kanji: "前", kana: "まえ", romaji: "mae", meaning: "before; front", level: "N5" },
  { kanji: "後", kana: "あと", romaji: "ato", meaning: "after; behind", level: "N5" },
  { kanji: "今", kana: "いま", romaji: "ima", meaning: "now", level: "N5" },
  { kanji: "一", kana: "いち", romaji: "ichi", meaning: "one", level: "N5" },
  { kanji: "二", kana: "に", romaji: "ni", meaning: "two", level: "N5" },
  { kanji: "三", kana: "さん", romaji: "san", meaning: "three", level: "N5" },
  { kanji: "四", kana: "よん", romaji: "yon", meaning: "four", level: "N5" },
  { kanji: "五", kana: "ご", romaji: "go", meaning: "five", level: "N5" },
  { kanji: "六", kana: "ろく", romaji: "roku", meaning: "six", level: "N5" },
  { kanji: "七", kana: "なな", romaji: "nana", meaning: "seven", level: "N5" },
  { kanji: "八", kana: "はち", romaji: "hachi", meaning: "eight", level: "N5" },
  { kanji: "九", kana: "きゅう", romaji: "kyuu", meaning: "nine", level: "N5" },
  { kanji: "十", kana: "じゅう", romaji: "juu", meaning: "ten", level: "N5" },
  { kanji: "百", kana: "ひゃく", romaji: "hyaku", meaning: "hundred", level: "N5" },
  { kanji: "千", kana: "せん", romaji: "sen", meaning: "thousand", level: "N5" },
  { kanji: "万", kana: "まん", romaji: "man", meaning: "ten thousand", level: "N5" },
  { kanji: "円", kana: "えん", romaji: "en", meaning: "yen", level: "N5" },
  { kanji: "日", kana: "にち", romaji: "nichi", meaning: "day; sun", level: "N5" },
  { kanji: "月", kana: "げつ", romaji: "getsu", meaning: "month; moon", level: "N5" },
  { kanji: "火", kana: "か", romaji: "ka", meaning: "fire", level: "N5" },
  { kanji: "水", kana: "すい", romaji: "sui", meaning: "water", level: "N5" },
  { kanji: "木", kana: "もく", romaji: "moku", meaning: "tree", level: "N5" },
  { kanji: "金", kana: "きん", romaji: "kin", meaning: "gold; money", level: "N5" },
  { kanji: "土", kana: "ど", romaji: "do", meaning: "earth", level: "N5" },
  { kanji: "人", kana: "ひと", romaji: "hito", meaning: "person", level: "N5" },
  { kanji: "子", kana: "こ", romaji: "ko", meaning: "child", level: "N5" },
  { kanji: "女", kana: "おんな", romaji: "onna", meaning: "woman", level: "N5" },
  { kanji: "男", kana: "おとこ", romaji: "otoko", meaning: "man", level: "N5" },
  { kanji: "山", kana: "やま", romaji: "yama", meaning: "mountain", level: "N5" },
  { kanji: "川", kana: "かわ", romaji: "kawa", meaning: "river", level: "N5" },
  { kanji: "田", kana: "た", romaji: "ta", meaning: "rice field", level: "N5" },
  { kanji: "口", kana: "くち", romaji: "kuchi", meaning: "mouth", level: "N5" },
  { kanji: "目", kana: "め", romaji: "me", meaning: "eye", level: "N5" },
  { kanji: "耳", kana: "みみ", romaji: "mimi", meaning: "ear", level: "N5" },
  { kanji: "手", kana: "て", romaji: "te", meaning: "hand", level: "N5" },
  { kanji: "足", kana: "あし", romaji: "ashi", meaning: "foot; leg", level: "N5" },
  { kanji: "力", kana: "ちから", romaji: "chikara", meaning: "power", level: "N5" },
  { kanji: "上", kana: "うえ", romaji: "ue", meaning: "up; above", level: "N5" },
  { kanji: "下", kana: "した", romaji: "shita", meaning: "down; below", level: "N5" },
  { kanji: "中", kana: "なか", romaji: "naka", meaning: "inside; middle", level: "N5" },
  { kanji: "大", kana: "おお", romaji: "oo", meaning: "big", level: "N5" },
  { kanji: "小", kana: "ちい", romaji: "chii", meaning: "small", level: "N5" },
  { kanji: "左", kana: "ひだり", romaji: "hidari", meaning: "left", level: "N5" },
  { kanji: "右", kana: "みぎ", romaji: "migi", meaning: "right", level: "N5" },
  { kanji: "東", kana: "ひがし", romaji: "higashi", meaning: "east", level: "N5" },
  { kanji: "西", kana: "にし", romaji: "nishi", meaning: "west", level: "N5" },
  { kanji: "南", kana: "みなみ", romaji: "minami", meaning: "south", level: "N5" },
  { kanji: "北", kana: "きた", romaji: "kita", meaning: "north", level: "N5" },
  { kanji: "学", kana: "がく", romaji: "gaku", meaning: "study", level: "N5" },
  { kanji: "生", kana: "せい", romaji: "sei", meaning: "life; birth", level: "N5" },
  { kanji: "先", kana: "せん", romaji: "sen", meaning: "previous; ahead", level: "N5" },
  { kanji: "校", kana: "こう", romaji: "kou", meaning: "school", level: "N5" },
  { kanji: "本", kana: "ほん", romaji: "hon", meaning: "book; origin", level: "N5" },
  { kanji: "名", kana: "な", romaji: "na", meaning: "name", level: "N5" },
  { kanji: "年", kana: "ねん", romaji: "nen", meaning: "year", level: "N5" },
  { kanji: "時", kana: "じ", romaji: "ji", meaning: "time; hour", level: "N5" },
  { kanji: "分", kana: "ふん", romaji: "fun", meaning: "minute; part", level: "N5" },
  { kanji: "半", kana: "はん", romaji: "han", meaning: "half", level: "N5" },
  { kanji: "何", kana: "なに", romaji: "nani", meaning: "what", level: "N5" },
  { kanji: "行", kana: "い", romaji: "i", meaning: "go", level: "N5" },
  { kanji: "来", kana: "く", romaji: "ku", meaning: "come", level: "N5" },
  { kanji: "帰", kana: "かえ", romaji: "kae", meaning: "return", level: "N5" },
  { kanji: "入", kana: "はい", romaji: "hai", meaning: "enter", level: "N5" },
  { kanji: "出", kana: "で", romaji: "de", meaning: "exit; leave", level: "N5" },
  { kanji: "会", kana: "あ", romaji: "a", meaning: "meet", level: "N5" },
  { kanji: "話", kana: "はな", romaji: "hana", meaning: "talk", level: "N5" },
  { kanji: "言", kana: "い", romaji: "i", meaning: "say", level: "N5" },
  { kanji: "読", kana: "よ", romaji: "yo", meaning: "read", level: "N5" },
  { kanji: "書", kana: "か", romaji: "ka", meaning: "write", level: "N5" },
  { kanji: "聞", kana: "き", romaji: "ki", meaning: "hear; ask", level: "N5" },
  { kanji: "見", kana: "み", romaji: "mi", meaning: "see", level: "N5" },
  { kanji: "食", kana: "た", romaji: "ta", meaning: "eat", level: "N5" },
  { kanji: "飲", kana: "の", romaji: "no", meaning: "drink", level: "N5" },
  { kanji: "買", kana: "か", romaji: "ka", meaning: "buy", level: "N5" },
  { kanji: "売", kana: "う", romaji: "u", meaning: "sell", level: "N5" },
  { kanji: "休", kana: "やす", romaji: "yasu", meaning: "rest", level: "N5" },
  { kanji: "好", kana: "す", romaji: "su", meaning: "like", level: "N5" },

  // Family & People
  { kanji: "父", kana: "ちち", romaji: "chichi", meaning: "father", level: "N5" },
  { kanji: "母", kana: "はは", romaji: "haha", meaning: "mother", level: "N5" },
  { kanji: "兄", kana: "あに", romaji: "ani", meaning: "older brother", level: "N5" },
  { kanji: "姉", kana: "あね", romaji: "ane", meaning: "older sister", level: "N5" },
  { kanji: "弟", kana: "おとうと", romaji: "otouto", meaning: "younger brother", level: "N5" },
  { kanji: "妹", kana: "いもうと", romaji: "imouto", meaning: "younger sister", level: "N5" },
  { kanji: "友", kana: "とも", romaji: "tomo", meaning: "friend", level: "N5" },

  // Food
  { kanji: "米", kana: "こめ", romaji: "kome", meaning: "rice", level: "N5" },
  { kanji: "肉", kana: "にく", romaji: "niku", meaning: "meat", level: "N5" },
  { kanji: "茶", kana: "ちゃ", romaji: "cha", meaning: "tea", level: "N5" },
  { kanji: "酒", kana: "さけ", romaji: "sake", meaning: "alcohol", level: "N4" },
  { kanji: "牛", kana: "うし", romaji: "ushi", meaning: "cow", level: "N5" },
  { kanji: "鳥", kana: "とり", romaji: "tori", meaning: "bird", level: "N5" },
  { kanji: "魚", kana: "さかな", romaji: "sakana", meaning: "fish", level: "N5" },

  // Animals
  { kanji: "犬", kana: "いぬ", romaji: "inu", meaning: "dog", level: "N5" },
  { kanji: "猫", kana: "ねこ", romaji: "neko", meaning: "cat", level: "N4" },

  // Colours
  { kanji: "白", kana: "しろ", romaji: "shiro", meaning: "white", level: "N5" },
  { kanji: "黒", kana: "くろ", romaji: "kuro", meaning: "black", level: "N5" },
  { kanji: "赤", kana: "あか", romaji: "aka", meaning: "red", level: "N5" },
  { kanji: "青", kana: "あお", romaji: "ao", meaning: "blue", level: "N5" },

  // Common Verbs
  { kanji: "持", kana: "も", romaji: "mo", meaning: "hold", level: "N5" },
  { kanji: "使", kana: "つか", romaji: "tsuka", meaning: "use", level: "N5" },
  { kanji: "待", kana: "ま", romaji: "ma", meaning: "wait", level: "N5" },
  { kanji: "思", kana: "おも", romaji: "omo", meaning: "think", level: "N5" },
  { kanji: "知", kana: "し", romaji: "shi", meaning: "know", level: "N5" },
  { kanji: "作", kana: "つく", romaji: "tsuku", meaning: "make", level: "N5" },
  { kanji: "住", kana: "す", romaji: "su", meaning: "live", level: "N5" },
  { kanji: "働", kana: "はたら", romaji: "hatara", meaning: "work", level: "N4" },
  { kanji: "起", kana: "お", romaji: "o", meaning: "wake up; rise", level: "N5" },
  { kanji: "寝", kana: "ね", romaji: "ne", meaning: "sleep", level: "N5" },
  { kanji: "着", kana: "き", romaji: "ki", meaning: "wear; arrive", level: "N5" },

  // Directions & Position
  { kanji: "内", kana: "うち", romaji: "uchi", meaning: "inside", level: "N5" },
  { kanji: "外", kana: "そと", romaji: "soto", meaning: "outside", level: "N5" },
  { kanji: "近", kana: "ちか", romaji: "chika", meaning: "near", level: "N5" },
  { kanji: "遠", kana: "とお", romaji: "too", meaning: "far", level: "N5" },

  // Descriptive
  { kanji: "明", kana: "あか", romaji: "aka", meaning: "bright", level: "N5" },
  { kanji: "暗", kana: "くら", romaji: "kura", meaning: "dark", level: "N4" },
  { kanji: "強", kana: "つよ", romaji: "tsuyo", meaning: "strong", level: "N5" },
  { kanji: "弱", kana: "よわ", romaji: "yowa", meaning: "weak", level: "N5" },
  { kanji: "早", kana: "はや", romaji: "haya", meaning: "early", level: "N5" },
  { kanji: "遅", kana: "おそ", romaji: "oso", meaning: "late", level: "N4" },

  // High-frequency Building Blocks
  { kanji: "用", kana: "よう", romaji: "you", meaning: "use", level: "N5" },
  { kanji: "要", kana: "よう", romaji: "you", meaning: "necessary", level: "N4" },
  { kanji: "定", kana: "てい", romaji: "tei", meaning: "fixed; decide", level: "N4" },
  { kanji: "意", kana: "い", romaji: "i", meaning: "idea; intention", level: "N4" },
  { kanji: "味", kana: "あじ", romaji: "aji", meaning: "taste", level: "N4" },
  { kanji: "利", kana: "り", romaji: "ri", meaning: "benefit", level: "N4" },
  { kanji: "必", kana: "ひつ", romaji: "hitsu", meaning: "certain; necessary", level: "N4" },
  { kanji: "無", kana: "む", romaji: "mu", meaning: "nothing; without", level: "N4" },
  { kanji: "有", kana: "ゆう", romaji: "yuu", meaning: "exist; have", level: "N4" },

  // Common Components
  { kanji: "屋", kana: "や", romaji: "ya", meaning: "shop; roof", level: "N4" },
  { kanji: "室", kana: "しつ", romaji: "shitsu", meaning: "room", level: "N5" },
  { kanji: "面", kana: "めん", romaji: "men", meaning: "face; surface", level: "N4" },
  { kanji: "方", kana: "かた", romaji: "kata", meaning: "direction; person", level: "N5" },
  { kanji: "品", kana: "ひん", romaji: "hin", meaning: "goods; article", level: "N4" },
  { kanji: "番", kana: "ばん", romaji: "ban", meaning: "number; turn", level: "N5" },
  { kanji: "区", kana: "く", romaji: "ku", meaning: "ward; district", level: "N4" },
  { kanji: "県", kana: "けん", romaji: "ken", meaning: "prefecture", level: "N4" },
  { kanji: "市", kana: "し", romaji: "shi", meaning: "city", level: "N5" },

  // Health
  { kanji: "病", kana: "びょう", romaji: "byou", meaning: "illness", level: "N5" },
  { kanji: "院", kana: "いん", romaji: "in", meaning: "institution", level: "N4" },
  { kanji: "薬", kana: "くすり", romaji: "kusuri", meaning: "medicine", level: "N4" },

  // Money
  { kanji: "銀", kana: "ぎん", romaji: "gin", meaning: "silver", level: "N5" },
  { kanji: "代", kana: "だい", romaji: "dai", meaning: "substitute; generation; fee", level: "N5" },
  { kanji: "値", kana: "ね", romaji: "ne", meaning: "value; price", level: "N4" },
  // Missing High-Frequency Kanji
  { kanji: "風", kana: "かぜ", romaji: "kaze", meaning: "wind", level: "N5" },
  { kanji: "海", kana: "うみ", romaji: "umi", meaning: "sea", level: "N5" },
  { kanji: "旅", kana: "たび", romaji: "tabi", meaning: "trip; travel", level: "N4" },
  { kanji: "写", kana: "うつ", romaji: "utsu", meaning: "copy; photograph", level: "N5" },
  { kanji: "真", kana: "ま", romaji: "ma", meaning: "true", level: "N4" },
  { kanji: "紙", kana: "かみ", romaji: "kami", meaning: "paper", level: "N5" },
  { kanji: "服", kana: "ふく", romaji: "fuku", meaning: "clothes", level: "N5" },
  { kanji: "色", kana: "いろ", romaji: "iro", meaning: "colour", level: "N5" },
  { kanji: "村", kana: "むら", romaji: "mura", meaning: "village", level: "N5" },
  { kanji: "町", kana: "まち", romaji: "machi", meaning: "town", level: "N5" },
  { kanji: "都", kana: "と", romaji: "to", meaning: "metropolis", level: "N4" },
  { kanji: "図", kana: "ず", romaji: "zu", meaning: "diagram", level: "N5" },
  { kanji: "館", kana: "かん", romaji: "kan", meaning: "building; hall", level: "N4" },
  { kanji: "線", kana: "せん", romaji: "sen", meaning: "line", level: "N4" },
  { kanji: "乗", kana: "の", romaji: "no", meaning: "ride", level: "N5" },
  { kanji: "降", kana: "お", romaji: "o", meaning: "get off; descend", level: "N4" },
  { kanji: "切", kana: "き", romaji: "ki", meaning: "cut", level: "N5" },
  { kanji: "押", kana: "お", romaji: "o", meaning: "push", level: "N4" },
  { kanji: "引", kana: "ひ", romaji: "hi", meaning: "pull", level: "N5" },
  { kanji: "拾", kana: "ひろ", romaji: "hiro", meaning: "pick up", level: "N3" },
];	

export const n5Kanji: Kanji[] = [
  { kanji: "怖い", kana: "こわい", romaji: "kowai", meaning: "scared", level: "N5" },
  { kanji: "一", kana: "いち", romaji: "ichi", meaning: "one", level: "N5" },
  { kanji: "二", kana: "に", romaji: "ni", meaning: "two", level: "N5" },
  { kanji: "三", kana: "さん", romaji: "san", meaning: "three", level: "N5" },
  { kanji: "山", kana: "やま", romaji: "yama", meaning: "mountain", level: "N5" },
  { kanji: "川", kana: "かわ", romaji: "kawa", meaning: "river", level: "N5" },
  { kanji: "海", kana: "うみ", romaji: "umi", meaning: "sea", level: "N5" },
  { kanji: "空", kana: "そら", romaji: "sora", meaning: "sky", level: "N5" },
  { kanji: "水", kana: "みず", romaji: "mizu", meaning: "water", level: "N5" },
  { kanji: "火", kana: "ひ", romaji: "hi", meaning: "fire", level: "N5" },
  { kanji: "木", kana: "き", romaji: "ki", meaning: "tree", level: "N5" },
  { kanji: "口", kana: "くち", romaji: "kuchi", meaning: "mouth", level: "N5" },
  { kanji: "目", kana: "め", romaji: "me", meaning: "eye", level: "N5" },
  { kanji: "耳", kana: "みみ", romaji: "mimi", meaning: "ear", level: "N5" },
  { kanji: "手", kana: "て", romaji: "te", meaning: "hand", level: "N5" },
  { kanji: "足", kana: "あし", romaji: "ashi", meaning: "foot", level: "N5" },
  { kanji: "上", kana: "うえ", romaji: "ue", meaning: "up / above", level: "N5" },
  { kanji: "下", kana: "した", romaji: "shita", meaning: "down / below", level: "N5" },
  { kanji: "中", kana: "なか", romaji: "naka", meaning: "inside / middle", level: "N5" },
  { kanji: "外", kana: "そと", romaji: "soto", meaning: "outside", level: "N5" },
  { kanji: "前", kana: "まえ", romaji: "mae", meaning: "front / before", level: "N5" },
  { kanji: "後", kana: "あと", romaji: "ato", meaning: "after / behind", level: "N5" },
  { kanji: "学校", kana: "がっこう", romaji: "gakkou", meaning: "school", level: "N5" },
  { kanji: "学生", kana: "がくせい", romaji: "gakusei", meaning: "student", level: "N5" },
  { kanji: "先生", kana: "せんせい", romaji: "sensei", meaning: "teacher", level: "N5" },
  { kanji: "日本", kana: "にほん", romaji: "nihon", meaning: "Japan", level: "N5" },
  { kanji: "今日", kana: "きょう", romaji: "kyou", meaning: "today", level: "N5" },
  { kanji: "明日", kana: "あした", romaji: "ashita", meaning: "tomorrow", level: "N5" },
  { kanji: "昨日", kana: "きのう", romaji: "kinou", meaning: "yesterday", level: "N5" },
  { kanji: "時間", kana: "じかん", romaji: "jikan", meaning: "time", level: "N5" },
  { kanji: "時計", kana: "とけい", romaji: "tokei", meaning: "clock / watch", level: "N5" },
  { kanji: "電車", kana: "でんしゃ", romaji: "densha", meaning: "train", level: "N5" },
  { kanji: "電話", kana: "でんわ", romaji: "denwa", meaning: "telephone", level: "N5" },
  { kanji: "自転車", kana: "じてんしゃ", romaji: "jitensha", meaning: "bicycle", level: "N5" },
  { kanji: "銀行", kana: "ぎんこう", romaji: "ginkou", meaning: "bank", level: "N5" },
  { kanji: "病院", kana: "びょういん", romaji: "byouin", meaning: "hospital", level: "N5" },
  { kanji: "郵便局", kana: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "post office", level: "N5" },
  { kanji: "会社", kana: "かいしゃ", romaji: "kaisha", meaning: "company", level: "N5" },
  { kanji: "会社員", kana: "かいしゃいん", romaji: "kaishain", meaning: "company employee", level: "N5" },
  { kanji: "友達", kana: "ともだち", romaji: "tomodachi", meaning: "friend", level: "N5" },
  { kanji: "家族", kana: "かぞく", romaji: "kazoku", meaning: "family", level: "N5" },
  { kanji: "毎日", kana: "まいにち", romaji: "mainichi", meaning: "every day", level: "N5" },
  { kanji: "毎週", kana: "まいしゅう", romaji: "maishuu", meaning: "every week", level: "N5" },
  { kanji: "毎月", kana: "まいつき", romaji: "maitsuki", meaning: "every month", level: "N5" },
  { kanji: "食事", kana: "しょくじ", romaji: "shokuji", meaning: "meal", level: "N5" },
  { kanji: "飲み物", kana: "のみもの", romaji: "nomimono", meaning: "drink", level: "N5" },
  { kanji: "読書", kana: "どくしょ", romaji: "dokusho", meaning: "reading", level: "N5" },
  { kanji: "大学", kana: "だいがく", romaji: "daigaku", meaning: "university", level: "N5" },
  { kanji: "高校", kana: "こうこう", romaji: "koukou", meaning: "high school", level: "N5" },
  { kanji: "教室", kana: "きょうしつ", romaji: "kyoushitsu", meaning: "classroom", level: "N5" },
  { kanji: "図書館", kana: "としょかん", romaji: "toshokan", meaning: "library", level: "N5" },
  { kanji: "本屋", kana: "ほんや", romaji: "honya", meaning: "bookstore", level: "N5" },
  { kanji: "仕事", kana: "しごと", romaji: "shigoto", meaning: "work, job", level: "N5" },
  { kanji: "社員", kana: "しゃいん", romaji: "shain", meaning: "employee", level: "N5" },
  { kanji: "駅前", kana: "えきまえ", romaji: "ekimae", meaning: "in front of the station", level: "N5" },
  { kanji: "入口", kana: "いりぐち", romaji: "iriguchi", meaning: "entrance", level: "N5" },
  { kanji: "出口", kana: "でぐち", romaji: "deguchi", meaning: "exit", level: "N5" },
  { kanji: "外国", kana: "がいこく", romaji: "gaikoku", meaning: "foreign country", level: "N5" },
  { kanji: "外国人", kana: "がいこくじん", romaji: "gaikokujin", meaning: "foreigner", level: "N5" },
  { kanji: "日本人", kana: "にほんじん", romaji: "nihonjin", meaning: "Japanese person", level: "N5" },
  { kanji: "朝", kana: "あさ", romaji: "asa", meaning: "morning", level: "N5" },
  { kanji: "昼", kana: "ひる", romaji: "hiru", meaning: "noon", level: "N5" },
  { kanji: "夜", kana: "よる", romaji: "yoru", meaning: "night", level: "N5" },
  { kanji: "今朝", kana: "けさ", romaji: "kesa", meaning: "this morning", level: "N5" },
  { kanji: "今晩", kana: "こんばん", romaji: "konban", meaning: "this evening", level: "N5" },
  { kanji: "今年", kana: "ことし", romaji: "kotoshi", meaning: "this year", level: "N5" },
  { kanji: "来年", kana: "らいねん", romaji: "rainen", meaning: "next year", level: "N5" },
  { kanji: "去年", kana: "きょねん", romaji: "kyonen", meaning: "last year", level: "N5" },
  { kanji: "今月", kana: "こんげつ", romaji: "kongetsu", meaning: "this month", level: "N5" },
  { kanji: "来月", kana: "らいげつ", romaji: "raigetsu", meaning: "next month", level: "N5" },
  { kanji: "先月", kana: "せんげつ", romaji: "sengetsu", meaning: "last month", level: "N5" },
  { kanji: "名前", kana: "なまえ", romaji: "namae", meaning: "name", level: "N5" },
  { kanji: "住所", kana: "じゅうしょ", romaji: "juusho", meaning: "address", level: "N5" },
  { kanji: "番号", kana: "ばんごう", romaji: "bangou", meaning: "number", level: "N5" },
  { kanji: "白", kana: "しろ", romaji: "shiro", meaning: "white", level: "N5" },
  { kanji: "黒", kana: "くろ", romaji: "kuro", meaning: "black", level: "N5" },
  { kanji: "赤", kana: "あか", romaji: "aka", meaning: "red", level: "N5" },
  { kanji: "青", kana: "あお", romaji: "ao", meaning: "blue", level: "N5" },
  { kanji: "先生方", kana: "せんせいがた", romaji: "senseigata", meaning: "teachers", level: "N5" },
  { kanji: "食堂", kana: "しょくどう", romaji: "shokudou", meaning: "cafeteria", level: "N5" },
  { kanji: "料理", kana: "りょうり", romaji: "ryouri", meaning: "cooking, cuisine", level: "N5" },
  { kanji: "牛肉", kana: "ぎゅうにく", romaji: "gyuuniku", meaning: "beef", level: "N5" },
  { kanji: "魚", kana: "さかな", romaji: "sakana", meaning: "fish", level: "N5" },
  { kanji: "野菜", kana: "やさい", romaji: "yasai", meaning: "vegetables", level: "N5" },
  { kanji: "雨", kana: "あめ", romaji: "ame", meaning: "rain", level: "N5" },
  { kanji: "雪", kana: "ゆき", romaji: "yuki", meaning: "snow", level: "N5" },
  { kanji: "天気", kana: "てんき", romaji: "tenki", meaning: "weather", level: "N5" },
  { kanji: "北", kana: "きた", romaji: "kita", meaning: "north", level: "N5" },
  { kanji: "南", kana: "みなみ", romaji: "minami", meaning: "south", level: "N5" },
  { kanji: "東", kana: "ひがし", romaji: "higashi", meaning: "east", level: "N5" },
  { kanji: "西", kana: "にし", romaji: "nishi", meaning: "west", level: "N5" },
  { kanji: "音楽", kana: "おんがく", romaji: "ongaku", meaning: "music", level: "N5" },
  { kanji: "映画", kana: "えいが", romaji: "eiga", meaning: "movie", level: "N5" },
  { kanji: "写真", kana: "しゃしん", romaji: "shashin", meaning: "photograph", level: "N5" },
  { kanji: "旅行", kana: "りょこう", romaji: "ryokou", meaning: "trip", level: "N5" },
  { kanji: "新", kana: "あたらしい", romaji: "atarashii", meaning: "new", level: "N5" },
  { kanji: "古", kana: "ふるい", romaji: "furui", meaning: "old", level: "N5" },
  { kanji: "長", kana: "ながい", romaji: "nagai", meaning: "long", level: "N5" },
  { kanji: "高", kana: "たかい", romaji: "takai", meaning: "high, expensive", level: "N5" },
  { kanji: "安", kana: "やすい", romaji: "yasui", meaning: "cheap", level: "N5" },
  { kanji: "多", kana: "おおい", romaji: "ooi", meaning: "many", level: "N5" },
  { kanji: "少", kana: "すくない", romaji: "sukunai", meaning: "few", level: "N5" },
  { kanji: "買物", kana: "かいもの", romaji: "kaimono", meaning: "shopping", level: "N5" },
  { kanji: "買", kana: "かう", romaji: "kau", meaning: "buy", level: "N5" },
  { kanji: "売", kana: "うる", romaji: "uru", meaning: "sell", level: "N5" },
  { kanji: "教科書", kana: "きょうかしょ", romaji: "kyoukasho", meaning: "textbook", level: "N5" },
  { kanji: "辞書", kana: "じしょ", romaji: "jisho", meaning: "dictionary", level: "N5" },
  { kanji: "宿題", kana: "しゅくだい", romaji: "shukudai", meaning: "homework", level: "N5" },
  { kanji: "問題", kana: "もんだい", romaji: "mondai", meaning: "question / problem", level: "N5" },
  { kanji: "試験", kana: "しけん", romaji: "shiken", meaning: "exam", level: "N5" },
  { kanji: "場所", kana: "ばしょ", romaji: "basho", meaning: "place", level: "N5" },
  { kanji: "近所", kana: "きんじょ", romaji: "kinjo", meaning: "neighborhood", level: "N5" },
  { kanji: "家", kana: "いえ", romaji: "ie", meaning: "house", level: "N5" },
  { kanji: "部屋", kana: "へや", romaji: "heya", meaning: "room", level: "N5" },
  { kanji: "台所", kana: "だいどころ", romaji: "daidokoro", meaning: "kitchen", level: "N5" },
  { kanji: "玄関", kana: "げんかん", romaji: "genkan", meaning: "entrance", level: "N5" },
  { kanji: "両親", kana: "りょうしん", romaji: "ryoushin", meaning: "parents", level: "N5" },
  { kanji: "夫婦", kana: "ふうふ", romaji: "fuufu", meaning: "married couple", level: "N5" },
  { kanji: "毎朝", kana: "まいあさ", romaji: "maiasa", meaning: "every morning", level: "N5" },
  { kanji: "毎晩", kana: "まいばん", romaji: "maiban", meaning: "every night", level: "N5" },
  { kanji: "午後", kana: "ごご", romaji: "gogo", meaning: "afternoon / p.m.", level: "N5" },
  { kanji: "午前", kana: "ごぜん", romaji: "gozen", meaning: "morning / a.m.", level: "N5" },
  { kanji: "先週", kana: "せんしゅう", romaji: "senshuu", meaning: "last week", level: "N5" },
  { kanji: "来週", kana: "らいしゅう", romaji: "raishuu", meaning: "next week", level: "N5" },
  { kanji: "今週", kana: "こんしゅう", romaji: "konshuu", meaning: "this week", level: "N5" },
  { kanji: "毎年", kana: "まいとし", romaji: "maitoshi", meaning: "every year", level: "N5" },
  { kanji: "電気", kana: "でんき", romaji: "denki", meaning: "electricity", level: "N5" },
  { kanji: "切手", kana: "きって", romaji: "kitte", meaning: "postage stamp", level: "N5" },
  { kanji: "荷物", kana: "にもつ", romaji: "nimotsu", meaning: "luggage", level: "N5" },
  { kanji: "洋服", kana: "ようふく", romaji: "youfuku", meaning: "western clothes", level: "N5" },
  { kanji: "服", kana: "ふく", romaji: "fuku", meaning: "clothes", level: "N5" },
  { kanji: "帽子", kana: "ぼうし", romaji: "boushi", meaning: "hat", level: "N5" },
  { kanji: "靴", kana: "くつ", romaji: "kutsu", meaning: "shoes", level: "N5" },
  { kanji: "牛乳", kana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "milk", level: "N5" },
  { kanji: "果物", kana: "くだもの", romaji: "kudamono", meaning: "fruit", level: "N5" },
  { kanji: "飲物", kana: "のみもの", romaji: "nomimono", meaning: "drink", level: "N5" },
  { kanji: "肉", kana: "にく", romaji: "niku", meaning: "meat", level: "N5" },
  { kanji: "鳥肉", kana: "とりにく", romaji: "toriniku", meaning: "chicken meat", level: "N5" },
  { kanji: "音", kana: "おと", romaji: "oto", meaning: "sound", level: "N5" },
  { kanji: "歌", kana: "うた", romaji: "uta", meaning: "song", level: "N5" },
  { kanji: "文字", kana: "もじ", romaji: "moji", meaning: "letter / character", level: "N5" },
  { kanji: "漢字", kana: "かんじ", romaji: "kanji", meaning: "kanji", level: "N5" },
  { kanji: "質問", kana: "しつもん", romaji: "shitsumon", meaning: "question", level: "N5" },
  { kanji: "答", kana: "こたえ", romaji: "kotae", meaning: "answer", level: "N5" },
  { kanji: "結婚", kana: "けっこん", romaji: "kekkon", meaning: "marriage", level: "N5" },
  { kanji: "誕生日", kana: "たんじょうび", romaji: "tanjoubi", meaning: "birthday", level: "N5" },
  { kanji: "掃除", kana: "そうじ", romaji: "sooji", meaning: "to clean", level: "N5" },
  { kanji: "勉強", kana: "べんきょう", romaji: "benkyou", meaning: "study", level: "N5" },
  { kanji: "何回", kana: "なんかい", romaji: "nankai", meaning: "how many times", level: "N5" },
  { kanji: "遅れる", kana: "おくれる", romaji: "okureru", meaning: "to be late", level: "N5" },
  { kanji: "公園", kana: "こうえん", romaji: "kouen", meaning: "park", level: "N5" },
  { kanji: "弁当", kana: "べんとう", romaji: "bentou", meaning: "bento; japanese lunch box", level: "N5" },
  { kanji: "本当", kana: "ほんとう", romaji: "hontou", meaning: "really; truth", level: "N5" },
  { kanji: "起きる", kana: "おきる", romaji: "okiru", meaning: "to wake up", level: "N5" },
  { kanji: "静か", kana: "しずか", romaji: "shizuka", meaning: "quiet; peaceful", level: "N5" },
  { kanji: "急ぎ", kana: "いそぎ", romaji: "isogi", meaning: "hurry; with haste", level: "N5" },
  { kanji: "散歩", kana: "さんぽ", romaji: "sanpo", meaning: "walk; stroll", level: "N5" },
  { kanji: "味", kana: "あじ", romaji: "aji", meaning: "taste", level: "N5" },
  { kanji: "人", kana: "ひと", romaji: "hito", meaning: "person", level: "N5" },
  { kanji: "子", kana: "こ", romaji: "ko", meaning: "child", level: "N5" },
  { kanji: "女", kana: "おんな", romaji: "onna", meaning: "woman", level: "N5" },
  { kanji: "男", kana: "おとこ", romaji: "otoko", meaning: "man", level: "N5" },
  { kanji: "父", kana: "ちち", romaji: "chichi", meaning: "father", level: "N5" },
  { kanji: "母", kana: "はは", romaji: "haha", meaning: "mother", level: "N5" },
  { kanji: "兄", kana: "あに", romaji: "ani", meaning: "older brother", level: "N5" },
  { kanji: "姉", kana: "あね", romaji: "ane", meaning: "older sister", level: "N5" },
  { kanji: "弟", kana: "おとうと", romaji: "otouto", meaning: "younger brother", level: "N5" },
  { kanji: "妹", kana: "いもうと", romaji: "imouto", meaning: "younger sister", level: "N5" },
  { kanji: "犬", kana: "いぬ", romaji: "inu", meaning: "dog", level: "N5" },
  { kanji: "猫", kana: "ねこ", romaji: "neko", meaning: "cat", level: "N5" },
  { kanji: "花", kana: "はな", romaji: "hana", meaning: "flower", level: "N5" },
  { kanji: "草", kana: "くさ", romaji: "kusa", meaning: "grass", level: "N5" },
  { kanji: "石", kana: "いし", romaji: "ishi", meaning: "stone", level: "N5" },
  { kanji: "紙", kana: "かみ", romaji: "kami", meaning: "paper", level: "N5" },
  { kanji: "店", kana: "みせ", romaji: "mise", meaning: "shop", level: "N5" },
  { kanji: "道", kana: "みち", romaji: "michi", meaning: "road", level: "N5" },
  { kanji: "橋", kana: "はし", romaji: "hashi", meaning: "bridge", level: "N5" },
  { kanji: "車", kana: "くるま", romaji: "kuruma", meaning: "car", level: "N5" },
  { kanji: "立つ", kana: "たつ", romaji: "tatsu", meaning: "to stand", level: "N5" },
  { kanji: "座る", kana: "すわる", romaji: "suwaru", meaning: "to sit", level: "N5" },
  { kanji: "歩く", kana: "あるく", romaji: "aruku", meaning: "to walk", level: "N5" },
  { kanji: "走る", kana: "はしる", romaji: "hashiru", meaning: "to run", level: "N5" },
  { kanji: "書く", kana: "かく", romaji: "kaku", meaning: "to write", level: "N5" },
  { kanji: "見る", kana: "みる", romaji: "miru", meaning: "to see", level: "N5" },
  { kanji: "大丈夫", kana: "だいじょうぶ", romaji: "daijobu", meaning: "okay; problem-free", level: "N5" },
  { kanji: "軽い", kana: "かるい", romaji: "karui", meaning: "light; not heavy", level: "N5" },
  { kanji: "暑い", kana: "あつい", romaji: "atsui", meaning: "hot", level: "N5" },
  { kanji: "始める", kana: "はじめる", romaji: "hajimeru", meaning: "to start", level: "N5" },
  { kanji: "便利", kana: "べんり", romaji: "benri", meaning: "convenient; handy", level: "N5" },
  { kanji: "不便", kana: "ふべん", romaji: "fuben", meaning: "inconvenient  ", level: "N5" },
  { kanji: "運転", kana: "うんてん", romaji: "unten", meaning: "operate a machine; driving", level: "N5" },
  { kanji: "傘", kana: "かさ", romaji: "kasa", meaning: "umbrella", level: "N5" },
  { kanji: "運転手", kana: "うんてんしゅ", romaji: "untenshuu", meaning: "driver  ", level: "N5" },
  { kanji: "楽しい", kana: "たのしい", romaji: "tanoshii", meaning: "enjoyful  ", level: "N5" },
  { kanji: "重い", kana: "おもい", romaji: "omoi", meaning: "heavy", level: "N5" },
  { kanji: "寒い", kana: "さむい", romaji: "samui", meaning: "cold", level: "N5" },
  { kanji: "机", kana: "つくえ", romaji: "tsukue", meaning: "desk", level: "N5" },
  { kanji: "庭", kana: "にわ", romaji: "niwa", meaning: "garden", level: "N5" },
  { kanji: "狭い", kana: "せまい", romaji: "semai", meaning: "small; tight", level: "N5" },
  { kanji: "椅子", kana: "いす", romaji: "isu", meaning: "chair", level: "N5" }
];

export const n5Kanji_3: Kanji[] =[
  { kanji: "注文", kana: "ちゅうもん", romaji: "chuumon", meaning: "order", level: "N4" },
  { kanji: "定食", kana: "ていしょく", romaji: "teishoku", meaning: "set meal", level: "N4" },
  { kanji: "割引", kana: "わりびき", romaji: "waribiki", meaning: "discount", level: "N4" },
  { kanji: "無料", kana: "むりょう", romaji: "muryou", meaning: "free of charge", level: "N4" },
  { kanji: "有料", kana: "ゆうりょう", romaji: "yuuryou", meaning: "paid", level: "N4" },
  { kanji: "現金", kana: "げんきん", romaji: "genkin", meaning: "cash", level: "N4" },
  { kanji: "電子", kana: "でんし", romaji: "denshi", meaning: "electronic", level: "N4" },
  { kanji: "注文", kana: "ちゅうもん", romaji: "chuumon", meaning: "order", level: "N4" },
  { kanji: "定食", kana: "ていしょく", romaji: "teishoku", meaning: "set meal", level: "N4" },
  { kanji: "会計", kana: "かいけい", romaji: "kaikei", meaning: "bill; checkout", level: "N4" },
  { kanji: "立入禁止", kana: "たちいりきんし", romaji: "tachiirikinshi", meaning: "no entry", level: "N3" },
  { kanji: "使用中", kana: "しようちゅう", romaji: "shiyouchuu", meaning: "in use", level: "N4" },
  { kanji: "故障中", kana: "こしょうちゅう", romaji: "koshouchuu", meaning: "out of order", level: "N4" },
  { kanji: "到着", kana: "とうちゃく", romaji: "touchaku", meaning: "arrival", level: "N4" },
  { kanji: "出発", kana: "しゅっぱつ", romaji: "shuppatsu", meaning: "departure", level: "N4" },
  { kanji: "利用", kana: "りよう", romaji: "riyou", meaning: "use; utilization", level: "N4" },
  { kanji: "開始", kana: "かいし", romaji: "kaishi", meaning: "start; begin", level: "N4" },
  { kanji: "終了", kana: "しゅうりょう", romaji: "shuuryou", meaning: "finish; end", level: "N4" },
  { kanji: "全部", kana: "ぜんぶ", romaji: "zenbu", meaning: "all; everything", level: "N5" },
  { kanji: "冷蔵庫", kana: "れいぞうこ", romaji: "reizouko", meaning: "refrigerator", level: "N4" },
  { kanji: "洗面所", kana: "せんめんじょ", romaji: "senmenjo", meaning: "washroom", level: "N4" },
  { kanji: "家賃", kana: "やちん", romaji: "yachin", meaning: "rent", level: "N4" },
  { kanji: "到着", kana: "とうちゃく", romaji: "touchaku", meaning: "arrival", level: "N4" },
  { kanji: "発車", kana: "はっしゃ", romaji: "hassha", meaning: "departure (train)", level: "N4" },
]